// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cpp_unique_DeepState_TestHarness_generation.cpp and cpp_unique_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

CharacterVector cpp_unique(CharacterVector vect);

TEST(refinr_deepstate_test,cpp_unique_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector vect  = RcppDeepState_CharacterVector();
  std::string vect_t = "/home/akhila/fuzzer_packages/fuzzedpackages/refinr/inst/testfiles/cpp_unique/AFL_cpp_unique/afl_inputs/" + std::to_string(t) + "_vect.qs";
  qs::c_qsave(vect,vect_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vect values: "<< vect << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cpp_unique(vect);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
