// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// InterDist_DeepState_TestHarness_generation.cpp and InterDist_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix InterDist(NumericMatrix C_cumsum);

TEST(chickn_deepstate_test,InterDist_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix C_cumsum  = RcppDeepState_NumericMatrix();
  qs::c_qsave(C_cumsum,"/home/akhila/fuzzer_packages/fuzzedpackages/chickn/inst/testfiles/InterDist/inputs/C_cumsum.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "C_cumsum values: "<< C_cumsum << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    InterDist(C_cumsum);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
