// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// unjoin_cent_cosums_DeepState_TestHarness_generation.cpp and unjoin_cent_cosums_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix unjoin_cent_cosums(NumericMatrix ret3, NumericMatrix ret2);

TEST(fromo_deepstate_test,unjoin_cent_cosums_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix ret3  = RcppDeepState_NumericMatrix();
  qs::c_qsave(ret3,"/home/akhila/fuzzer_packages/fuzzedpackages/fromo/inst/testfiles/unjoin_cent_cosums/inputs/ret3.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ret3 values: "<< ret3 << std::endl;
  NumericMatrix ret2  = RcppDeepState_NumericMatrix();
  qs::c_qsave(ret2,"/home/akhila/fuzzer_packages/fuzzedpackages/fromo/inst/testfiles/unjoin_cent_cosums/inputs/ret2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ret2 values: "<< ret2 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    unjoin_cent_cosums(ret3,ret2);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
