// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// bifie_table1_character_DeepState_TestHarness_generation.cpp and bifie_table1_character_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List bifie_table1_character(Rcpp::CharacterVector datavec);

TEST(BIFIEsurvey_deepstate_test,bifie_table1_character_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector datavec  = RcppDeepState_CharacterVector();
  std::string datavec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifie_table1_character/AFL_bifie_table1_character/afl_inputs/" + std::to_string(t) + "_datavec.qs";
  qs::c_qsave(datavec,datavec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "datavec values: "<< datavec << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    bifie_table1_character(datavec);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
