// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ReleaseSelected__new_DeepState_TestHarness_generation.cpp and ReleaseSelected__new_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

SEXP ReleaseSelected__new(int id, int amount);

TEST(simmer_deepstate_test,ReleaseSelected__new_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector id(1);
  id[0]  = RcppDeepState_int();
  std::string id_t = "/home/akhila/fuzzer_packages/fuzzedpackages/simmer/inst/testfiles/ReleaseSelected__new/libFuzzer_ReleaseSelected__new/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_id.qs";
  qs::c_qsave(id,id_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "id values: "<< id << std::endl;
  IntegerVector amount(1);
  amount[0]  = RcppDeepState_int();
  std::string amount_t = "/home/akhila/fuzzer_packages/fuzzedpackages/simmer/inst/testfiles/ReleaseSelected__new/libFuzzer_ReleaseSelected__new/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_amount.qs";
  qs::c_qsave(amount,amount_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "amount values: "<< amount << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ReleaseSelected__new(id[0],amount[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
