// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// bifiesurvey_rcpp_bifiedata2bifiecdata_DeepState_TestHarness_generation.cpp and bifiesurvey_rcpp_bifiedata2bifiecdata_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List bifiesurvey_rcpp_bifiedata2bifiecdata(Rcpp::NumericMatrix datalistM, int Nimp);

TEST(BIFIEsurvey_deepstate_test,bifiesurvey_rcpp_bifiedata2bifiecdata_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix datalistM  = RcppDeepState_NumericMatrix();
  qs::c_qsave(datalistM,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_bifiedata2bifiecdata/inputs/datalistM.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "datalistM values: "<< datalistM << std::endl;
  IntegerVector Nimp(1);
  Nimp[0]  = RcppDeepState_int();
  qs::c_qsave(Nimp,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_bifiedata2bifiecdata/inputs/Nimp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Nimp values: "<< Nimp << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    bifiesurvey_rcpp_bifiedata2bifiecdata(datalistM,Nimp[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
