// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// kMeansBaryEps_DeepState_TestHarness_generation.cpp and kMeansBaryEps_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List kMeansBaryEps(NumericVector epsvec, NumericVector zetax, NumericVector zetay, NumericMatrix ppmatx, NumericMatrix ppmaty, double penalty, int add_del, IntegerVector relaxationVars, int N, double eps, int verbose);

TEST(ttbary_deepstate_test,kMeansBaryEps_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector epsvec  = RcppDeepState_NumericVector();
  qs::c_qsave(epsvec,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/epsvec.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "epsvec values: "<< epsvec << std::endl;
  NumericVector zetax  = RcppDeepState_NumericVector();
  qs::c_qsave(zetax,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/zetax.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "zetax values: "<< zetax << std::endl;
  NumericVector zetay  = RcppDeepState_NumericVector();
  qs::c_qsave(zetay,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/zetay.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "zetay values: "<< zetay << std::endl;
  NumericMatrix ppmatx  = RcppDeepState_NumericMatrix();
  qs::c_qsave(ppmatx,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/ppmatx.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ppmatx values: "<< ppmatx << std::endl;
  NumericMatrix ppmaty  = RcppDeepState_NumericMatrix();
  qs::c_qsave(ppmaty,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/ppmaty.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ppmaty values: "<< ppmaty << std::endl;
  NumericVector penalty(1);
  penalty[0]  = RcppDeepState_double();
  qs::c_qsave(penalty,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/penalty.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "penalty values: "<< penalty << std::endl;
  IntegerVector add_del(1);
  add_del[0]  = RcppDeepState_int();
  qs::c_qsave(add_del,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/add_del.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "add_del values: "<< add_del << std::endl;
  IntegerVector relaxationVars  = RcppDeepState_IntegerVector();
  qs::c_qsave(relaxationVars,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/relaxationVars.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "relaxationVars values: "<< relaxationVars << std::endl;
  IntegerVector N(1);
  N[0]  = RcppDeepState_int();
  qs::c_qsave(N,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/N.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "N values: "<< N << std::endl;
  NumericVector eps(1);
  eps[0]  = RcppDeepState_double();
  qs::c_qsave(eps,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/eps.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "eps values: "<< eps << std::endl;
  IntegerVector verbose(1);
  verbose[0]  = RcppDeepState_int();
  qs::c_qsave(verbose,"/home/akhila/fuzzer_packages/fuzzedpackages/ttbary/inst/testfiles/kMeansBaryEps/inputs/verbose.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "verbose values: "<< verbose << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    kMeansBaryEps(epsvec,zetax,zetay,ppmatx,ppmaty,penalty[0],add_del[0],relaxationVars,N[0],eps[0],verbose[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
