# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

profileloglik <- function(sigma, S, n) {
    .Call(`_covglasso_profileloglik`, sigma, S, n)
}

covglasso <- function(S, lambda, start, n, tolout, tolin, iterout, iterin) {
    .Call(`_covglasso_covglasso`, S, lambda, start, n, tolout, tolin, iterout, iterin)
}

covglassopath_bic <- function(S, lambda, start, L, n, tolout, tolin, iterout, iterin) {
    .Call(`_covglasso_covglassopath_bic`, S, lambda, start, L, n, tolout, tolin, iterout, iterin)
}

