// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// specificity_DeepState_TestHarness_generation.cpp and specificity_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

bool specificity(NumericVector x, NumericVector y, NumericVector vars, NumericMatrix specs);

TEST(lfl_deepstate_test,specificity_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/lfl/inst/testfiles/specificity/libFuzzer_specificity/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  std::string y_t = "/home/akhila/fuzzer_packages/fuzzedpackages/lfl/inst/testfiles/specificity/libFuzzer_specificity/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_y.qs";
  qs::c_qsave(y,y_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector vars  = RcppDeepState_NumericVector();
  std::string vars_t = "/home/akhila/fuzzer_packages/fuzzedpackages/lfl/inst/testfiles/specificity/libFuzzer_specificity/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_vars.qs";
  qs::c_qsave(vars,vars_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vars values: "<< vars << std::endl;
  NumericMatrix specs  = RcppDeepState_NumericMatrix();
  std::string specs_t = "/home/akhila/fuzzer_packages/fuzzedpackages/lfl/inst/testfiles/specificity/libFuzzer_specificity/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_specs.qs";
  qs::c_qsave(specs,specs_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "specs values: "<< specs << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    specificity(x,y,vars,specs);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
