// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// tam_rcpp_wle_errinv_DeepState_TestHarness_generation.cpp and tam_rcpp_wle_errinv_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericMatrix tam_rcpp_wle_errinv(Rcpp::NumericMatrix myERR, int cndim, int cnstud);

TEST(TAM_deepstate_test,tam_rcpp_wle_errinv_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix myERR  = RcppDeepState_NumericMatrix();
  std::string myERR_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TAM/inst/testfiles/tam_rcpp_wle_errinv/libFuzzer_tam_rcpp_wle_errinv/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_myERR.qs";
  qs::c_qsave(myERR,myERR_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "myERR values: "<< myERR << std::endl;
  IntegerVector cndim(1);
  cndim[0]  = RcppDeepState_int();
  std::string cndim_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TAM/inst/testfiles/tam_rcpp_wle_errinv/libFuzzer_tam_rcpp_wle_errinv/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cndim.qs";
  qs::c_qsave(cndim,cndim_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cndim values: "<< cndim << std::endl;
  IntegerVector cnstud(1);
  cnstud[0]  = RcppDeepState_int();
  std::string cnstud_t = "/home/akhila/fuzzer_packages/fuzzedpackages/TAM/inst/testfiles/tam_rcpp_wle_errinv/libFuzzer_tam_rcpp_wle_errinv/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cnstud.qs";
  qs::c_qsave(cnstud,cnstud_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cnstud values: "<< cnstud << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    tam_rcpp_wle_errinv(myERR,cndim[0],cnstud[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
