// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// dim_domain_subarray_DeepState_TestHarness_generation.cpp and dim_domain_subarray_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector dim_domain_subarray(NumericVector domain, NumericVector subscript);

TEST(tiledb_deepstate_test,dim_domain_subarray_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector domain  = RcppDeepState_NumericVector();
  qs::c_qsave(domain,"/home/akhila/fuzzer_packages/fuzzedpackages/tiledb/inst/testfiles/dim_domain_subarray/inputs/domain.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "domain values: "<< domain << std::endl;
  NumericVector subscript  = RcppDeepState_NumericVector();
  qs::c_qsave(subscript,"/home/akhila/fuzzer_packages/fuzzedpackages/tiledb/inst/testfiles/dim_domain_subarray/inputs/subscript.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "subscript values: "<< subscript << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    dim_domain_subarray(domain,subscript);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
