// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// func_mvt_ar_DeepState_TestHarness_generation.cpp and func_mvt_ar_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix func_mvt_ar(NumericMatrix ar, NumericMatrix res);

TEST(hdbinseg_deepstate_test,func_mvt_ar_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix ar  = RcppDeepState_NumericMatrix();
  qs::c_qsave(ar,"/home/akhila/fuzzer_packages/fuzzedpackages/hdbinseg/inst/testfiles/func_mvt_ar/inputs/ar.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ar values: "<< ar << std::endl;
  NumericMatrix res  = RcppDeepState_NumericMatrix();
  qs::c_qsave(res,"/home/akhila/fuzzer_packages/fuzzedpackages/hdbinseg/inst/testfiles/func_mvt_ar/inputs/res.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "res values: "<< res << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    func_mvt_ar(ar,res);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
