// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ChangePointAnalyzeNormUnRes_DeepState_TestHarness_generation.cpp and ChangePointAnalyzeNormUnRes_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector ChangePointAnalyzeNormUnRes(NumericVector Data, IntegerVector InputLength, NumericVector Prior);

TEST(StepSignalMargiLike_deepstate_test,ChangePointAnalyzeNormUnRes_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector Data  = RcppDeepState_NumericVector();
  std::string Data_t = "/home/akhila/fuzzer_packages/fuzzedpackages/StepSignalMargiLike/inst/testfiles/ChangePointAnalyzeNormUnRes/AFL_ChangePointAnalyzeNormUnRes/afl_inputs/" + std::to_string(t) + "_Data.qs";
  qs::c_qsave(Data,Data_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Data values: "<< Data << std::endl;
  IntegerVector InputLength  = RcppDeepState_IntegerVector();
  std::string InputLength_t = "/home/akhila/fuzzer_packages/fuzzedpackages/StepSignalMargiLike/inst/testfiles/ChangePointAnalyzeNormUnRes/AFL_ChangePointAnalyzeNormUnRes/afl_inputs/" + std::to_string(t) + "_InputLength.qs";
  qs::c_qsave(InputLength,InputLength_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "InputLength values: "<< InputLength << std::endl;
  NumericVector Prior  = RcppDeepState_NumericVector();
  std::string Prior_t = "/home/akhila/fuzzer_packages/fuzzedpackages/StepSignalMargiLike/inst/testfiles/ChangePointAnalyzeNormUnRes/AFL_ChangePointAnalyzeNormUnRes/afl_inputs/" + std::to_string(t) + "_Prior.qs";
  qs::c_qsave(Prior,Prior_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Prior values: "<< Prior << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ChangePointAnalyzeNormUnRes(Data,InputLength,Prior);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
