// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// unshelteredMidflameWindSpeed_DeepState_TestHarness_generation.cpp and unshelteredMidflameWindSpeed_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double unshelteredMidflameWindSpeed(double wind20H, double fuelBedHeight);

TEST(medfate_deepstate_test,unshelteredMidflameWindSpeed_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector wind20H(1);
  wind20H[0]  = RcppDeepState_double();
  std::string wind20H_t = "/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/unshelteredMidflameWindSpeed/libFuzzer_unshelteredMidflameWindSpeed/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_wind20H.qs";
  qs::c_qsave(wind20H,wind20H_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wind20H values: "<< wind20H << std::endl;
  NumericVector fuelBedHeight(1);
  fuelBedHeight[0]  = RcppDeepState_double();
  std::string fuelBedHeight_t = "/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/unshelteredMidflameWindSpeed/libFuzzer_unshelteredMidflameWindSpeed/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_fuelBedHeight.qs";
  qs::c_qsave(fuelBedHeight,fuelBedHeight_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fuelBedHeight values: "<< fuelBedHeight << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    unshelteredMidflameWindSpeed(wind20H[0],fuelBedHeight[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
