// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// get_A_DeepState_TestHarness_generation.cpp and get_A_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double get_A(double mu, double mu2, double mu3);

TEST(coga_deepstate_test,get_A_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector mu(1);
  mu[0]  = RcppDeepState_double();
  std::string mu_t = "/home/akhila/fuzzer_packages/fuzzedpackages/coga/inst/testfiles/get_A/libFuzzer_get_A/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu.qs";
  qs::c_qsave(mu,mu_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  NumericVector mu2(1);
  mu2[0]  = RcppDeepState_double();
  std::string mu_t = "/home/akhila/fuzzer_packages/fuzzedpackages/coga/inst/testfiles/get_A/libFuzzer_get_A/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu.qs";
  std::string mu2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/coga/inst/testfiles/get_A/libFuzzer_get_A/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu2.qs";
  qs::c_qsave(mu2,mu2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu2 values: "<< mu2 << std::endl;
  NumericVector mu3(1);
  mu3[0]  = RcppDeepState_double();
  std::string mu_t = "/home/akhila/fuzzer_packages/fuzzedpackages/coga/inst/testfiles/get_A/libFuzzer_get_A/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu.qs";
  std::string mu3_t = "/home/akhila/fuzzer_packages/fuzzedpackages/coga/inst/testfiles/get_A/libFuzzer_get_A/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu3.qs";
  qs::c_qsave(mu3,mu3_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu3 values: "<< mu3 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    get_A(mu[0],mu2[0],mu3[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
