// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// UH_DeepState_TestHarness_generation.cpp and UH_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector UH(int model, NumericVector Qg, NumericVector param);

TEST(HBV.IANIGLA_deepstate_test,UH_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector model(1);
  model[0]  = RcppDeepState_int();
  qs::c_qsave(model,"/home/akhila/fuzzer_packages/fuzzedpackages/HBV.IANIGLA/inst/testfiles/UH/inputs/model.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "model values: "<< model << std::endl;
  NumericVector Qg  = RcppDeepState_NumericVector();
  qs::c_qsave(Qg,"/home/akhila/fuzzer_packages/fuzzedpackages/HBV.IANIGLA/inst/testfiles/UH/inputs/Qg.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Qg values: "<< Qg << std::endl;
  NumericVector param  = RcppDeepState_NumericVector();
  qs::c_qsave(param,"/home/akhila/fuzzer_packages/fuzzedpackages/HBV.IANIGLA/inst/testfiles/UH/inputs/param.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "param values: "<< param << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    UH(model[0],Qg,param);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
