#!/bin/sh

set -o errexit
set -o nounset

if [ ! -e ./tools/autodep ]; then
  echo "$0 must be run from the top of the project tree"
  exit
fi

cd src && gcc -MM *.cpp | perl -pe 's,\bEigen[^\s]+, ,g' | perl -pe 's,^\s*\\\n,,' | perl -pe 's,:,: Makevars,' > autodep
