#!/bin/sh

set -o errexit
set -o nounset
set -o noclobber

if [ ! -x tools/rox ]; then
  echo "$0 must be run from the top of the package directory"
  exit 1
fi

Version=1.0.5
descVersion=$(grep Version DESCRIPTION | cut -d ' ' -f 2)
if [ "$descVersion" != "$Version" ]; then
  today=$(date +%Y-%m-%d)
  perl -pi -e "s/^Date\:.*$/Date: $today/;
               s/^Version\:.*$/Version: $Version/;" DESCRIPTION
fi

rm -f man/*.Rd
R --no-restore --no-save --no-readline <<EOF
library(roxygen2)
pkgload::load_all()
roxygenize('.', roclets=c("rd"))
EOF
