// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// diffuseSteveCpp_DeepState_TestHarness_generation.cpp and diffuseSteveCpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

void diffuseSteveCpp(Rcpp::NumericMatrix y, double D, double h, double tstep);

TEST(BacArena_deepstate_test,diffuseSteveCpp_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix y  = RcppDeepState_NumericMatrix();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/BacArena/inst/testfiles/diffuseSteveCpp/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector D(1);
  D[0]  = RcppDeepState_double();
  qs::c_qsave(D,"/home/akhila/fuzzer_packages/fuzzedpackages/BacArena/inst/testfiles/diffuseSteveCpp/inputs/D.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "D values: "<< D << std::endl;
  NumericVector h(1);
  h[0]  = RcppDeepState_double();
  qs::c_qsave(h,"/home/akhila/fuzzer_packages/fuzzedpackages/BacArena/inst/testfiles/diffuseSteveCpp/inputs/h.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "h values: "<< h << std::endl;
  NumericVector tstep(1);
  tstep[0]  = RcppDeepState_double();
  qs::c_qsave(tstep,"/home/akhila/fuzzer_packages/fuzzedpackages/BacArena/inst/testfiles/diffuseSteveCpp/inputs/tstep.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tstep values: "<< tstep << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    diffuseSteveCpp(y,D[0],h[0],tstep[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
