// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// temperatureChange_DeepState_TestHarness_generation.cpp and temperatureChange_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector temperatureChange(NumericVector dVec, NumericVector Temp, NumericVector sand, NumericVector clay, NumericVector W, NumericVector Theta_FC, double Gdown);

TEST(medfate_deepstate_test,temperatureChange_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector dVec  = RcppDeepState_NumericVector();
  qs::c_qsave(dVec,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/temperatureChange/inputs/dVec.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dVec values: "<< dVec << std::endl;
  NumericVector Temp  = RcppDeepState_NumericVector();
  qs::c_qsave(Temp,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/temperatureChange/inputs/Temp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Temp values: "<< Temp << std::endl;
  NumericVector sand  = RcppDeepState_NumericVector();
  qs::c_qsave(sand,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/temperatureChange/inputs/sand.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sand values: "<< sand << std::endl;
  NumericVector clay  = RcppDeepState_NumericVector();
  qs::c_qsave(clay,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/temperatureChange/inputs/clay.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "clay values: "<< clay << std::endl;
  NumericVector W  = RcppDeepState_NumericVector();
  qs::c_qsave(W,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/temperatureChange/inputs/W.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "W values: "<< W << std::endl;
  NumericVector Theta_FC  = RcppDeepState_NumericVector();
  qs::c_qsave(Theta_FC,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/temperatureChange/inputs/Theta_FC.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Theta_FC values: "<< Theta_FC << std::endl;
  NumericVector Gdown(1);
  Gdown[0]  = RcppDeepState_double();
  qs::c_qsave(Gdown,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/temperatureChange/inputs/Gdown.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Gdown values: "<< Gdown << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    temperatureChange(dVec,Temp,sand,clay,W,Theta_FC,Gdown[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
