// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// CPP_dsm_score_sparse_DeepState_TestHarness_generation.cpp and CPP_dsm_score_sparse_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector CPP_dsm_score_sparse(int nr, int nc, IntegerVector p, IntegerVector row_of, NumericVector f, NumericVector f1, NumericVector f2, double N, int am_code, int sparse, int transform_code);

TEST(wordspace_deepstate_test,CPP_dsm_score_sparse_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector nr(1);
  nr[0]  = RcppDeepState_int();
  qs::c_qsave(nr,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/nr.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nr values: "<< nr << std::endl;
  IntegerVector nc(1);
  nc[0]  = RcppDeepState_int();
  qs::c_qsave(nc,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/nc.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nc values: "<< nc << std::endl;
  IntegerVector p  = RcppDeepState_IntegerVector();
  qs::c_qsave(p,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/p.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p values: "<< p << std::endl;
  IntegerVector row_of  = RcppDeepState_IntegerVector();
  qs::c_qsave(row_of,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/row_of.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "row_of values: "<< row_of << std::endl;
  NumericVector f  = RcppDeepState_NumericVector();
  qs::c_qsave(f,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/f.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "f values: "<< f << std::endl;
  NumericVector f1  = RcppDeepState_NumericVector();
  qs::c_qsave(f1,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/f1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "f1 values: "<< f1 << std::endl;
  NumericVector f2  = RcppDeepState_NumericVector();
  qs::c_qsave(f2,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/f2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "f2 values: "<< f2 << std::endl;
  NumericVector N(1);
  N[0]  = RcppDeepState_double();
  qs::c_qsave(N,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/N.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "N values: "<< N << std::endl;
  IntegerVector am_code(1);
  am_code[0]  = RcppDeepState_int();
  qs::c_qsave(am_code,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/am_code.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "am_code values: "<< am_code << std::endl;
  IntegerVector sparse(1);
  sparse[0]  = RcppDeepState_int();
  qs::c_qsave(sparse,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/sparse.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sparse values: "<< sparse << std::endl;
  IntegerVector transform_code(1);
  transform_code[0]  = RcppDeepState_int();
  qs::c_qsave(transform_code,"/home/akhila/fuzzer_packages/fuzzedpackages/wordspace/inst/testfiles/CPP_dsm_score_sparse/inputs/transform_code.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "transform_code values: "<< transform_code << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    CPP_dsm_score_sparse(nr[0],nc[0],p,row_of,f,f1,f2,N[0],am_code[0],sparse[0],transform_code[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
