// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// eigenCpp
List eigenCpp(Eigen::Map<Eigen::MatrixXd> X);
RcppExport SEXP _iprior_eigenCpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(eigenCpp(X));
    return rcpp_result_gen;
END_RCPP
}
// fastSquare
Eigen::MatrixXd fastSquare(SEXP X);
RcppExport SEXP _iprior_fastSquare(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastSquare(X));
    return rcpp_result_gen;
END_RCPP
}
// fastSquareRoot
Eigen::MatrixXd fastSquareRoot(SEXP X);
RcppExport SEXP _iprior_fastSquareRoot(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fastSquareRoot(X));
    return rcpp_result_gen;
END_RCPP
}
// fastVDiag
NumericMatrix fastVDiag(NumericMatrix X, NumericVector y);
RcppExport SEXP _iprior_fastVDiag(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastVDiag(X, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iprior_eigenCpp", (DL_FUNC) &_iprior_eigenCpp, 1},
    {"_iprior_fastSquare", (DL_FUNC) &_iprior_fastSquare, 1},
    {"_iprior_fastSquareRoot", (DL_FUNC) &_iprior_fastSquareRoot, 1},
    {"_iprior_fastVDiag", (DL_FUNC) &_iprior_fastVDiag, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_iprior(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
