// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// CPL_sfc_from_wkt_DeepState_TestHarness_generation.cpp and CPL_sfc_from_wkt_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List CPL_sfc_from_wkt(Rcpp::CharacterVector wkt);

TEST(sf_deepstate_test,CPL_sfc_from_wkt_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector wkt  = RcppDeepState_CharacterVector();
  std::string wkt_t = "/home/akhila/fuzzer_packages/fuzzedpackages/sf/inst/testfiles/CPL_sfc_from_wkt/libFuzzer_CPL_sfc_from_wkt/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_wkt.qs";
  qs::c_qsave(wkt,wkt_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wkt values: "<< wkt << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    CPL_sfc_from_wkt(wkt);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
