// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cusum_DeepState_TestHarness_generation.cpp and cusum_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector cusum(NumericVector x, double X_bar);

TEST(ChangePointTaylor_deepstate_test,cusum_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ChangePointTaylor/inst/testfiles/cusum/libFuzzer_cusum/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector X_bar(1);
  X_bar[0]  = RcppDeepState_double();
  std::string X_bar_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ChangePointTaylor/inst/testfiles/cusum/libFuzzer_cusum/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_X_bar.qs";
  qs::c_qsave(X_bar,X_bar_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "X_bar values: "<< X_bar << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cusum(x,X_bar[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
