// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// mollweide_projection_DeepState_TestHarness_generation.cpp and mollweide_projection_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

DataFrame mollweide_projection(NumericVector latitude, NumericVector longitude, const double meridian);

TEST(glow_deepstate_test,mollweide_projection_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector latitude  = RcppDeepState_NumericVector();
  qs::c_qsave(latitude,"/home/akhila/fuzzer_packages/fuzzedpackages/glow/inst/testfiles/mollweide_projection/inputs/latitude.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "latitude values: "<< latitude << std::endl;
  NumericVector longitude  = RcppDeepState_NumericVector();
  qs::c_qsave(longitude,"/home/akhila/fuzzer_packages/fuzzedpackages/glow/inst/testfiles/mollweide_projection/inputs/longitude.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "longitude values: "<< longitude << std::endl;
  NumericVector meridian(1);
  meridian[0]  = RcppDeepState_double();
  qs::c_qsave(meridian,"/home/akhila/fuzzer_packages/fuzzedpackages/glow/inst/testfiles/mollweide_projection/inputs/meridian.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "meridian values: "<< meridian << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    mollweide_projection(latitude,longitude,meridian[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
