// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rlev_DeepState_TestHarness_generation.cpp and rlev_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector rlev(const int n, const double loc, const double scale);

TEST(teachingApps_deepstate_test,rlev_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/teachingApps/inst/testfiles/rlev/AFL_rlev/afl_inputs/" + std::to_string(t) + "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  NumericVector loc(1);
  loc[0]  = RcppDeepState_double();
  std::string loc_t = "/home/akhila/fuzzer_packages/fuzzedpackages/teachingApps/inst/testfiles/rlev/AFL_rlev/afl_inputs/" + std::to_string(t) + "_loc.qs";
  qs::c_qsave(loc,loc_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "loc values: "<< loc << std::endl;
  NumericVector scale(1);
  scale[0]  = RcppDeepState_double();
  std::string scale_t = "/home/akhila/fuzzer_packages/fuzzedpackages/teachingApps/inst/testfiles/rlev/AFL_rlev/afl_inputs/" + std::to_string(t) + "_scale.qs";
  qs::c_qsave(scale,scale_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "scale values: "<< scale << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rlev(n[0],loc[0],scale[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
