// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// init_context_DeepState_TestHarness_generation.cpp and init_context_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

SEXP init_context(int threads);

TEST(clustermq_deepstate_test,init_context_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector threads(1);
  threads[0]  = RcppDeepState_int();
  std::string threads_t = "/home/akhila/fuzzer_packages/fuzzedpackages/clustermq/inst/testfiles/init_context/libFuzzer_init_context/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_threads.qs";
  qs::c_qsave(threads,threads_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "threads values: "<< threads << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    init_context(threads[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
