// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sample_rcpp_DeepState_TestHarness_generation.cpp and sample_rcpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector sample_rcpp(int N, int nsamp);

TEST(perccal_deepstate_test,sample_rcpp_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector N(1);
  N[0]  = RcppDeepState_int();
  std::string N_t = "/home/akhila/fuzzer_packages/fuzzedpackages/perccal/inst/testfiles/sample_rcpp/libFuzzer_sample_rcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_N.qs";
  qs::c_qsave(N,N_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "N values: "<< N << std::endl;
  IntegerVector nsamp(1);
  nsamp[0]  = RcppDeepState_int();
  std::string nsamp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/perccal/inst/testfiles/sample_rcpp/libFuzzer_sample_rcpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nsamp.qs";
  qs::c_qsave(nsamp,nsamp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nsamp values: "<< nsamp << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sample_rcpp(N[0],nsamp[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
