// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// updateSubmat_DeepState_TestHarness_generation.cpp and updateSubmat_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix updateSubmat(NumericMatrix submat, NumericMatrix sublb_red);

TEST(BacArena_deepstate_test,updateSubmat_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix submat  = RcppDeepState_NumericMatrix();
  qs::c_qsave(submat,"/home/akhila/fuzzer_packages/fuzzedpackages/BacArena/inst/testfiles/updateSubmat/inputs/submat.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "submat values: "<< submat << std::endl;
  NumericMatrix sublb_red  = RcppDeepState_NumericMatrix();
  qs::c_qsave(sublb_red,"/home/akhila/fuzzer_packages/fuzzedpackages/BacArena/inst/testfiles/updateSubmat/inputs/sublb_red.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sublb_red values: "<< sublb_red << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    updateSubmat(submat,sublb_red);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
