#include <Rcpp.h>

using namespace Rcpp;
// [[Rcpp::export]]
List compnoreg(const int burnin, const int iteration,
	NumericVector t,
	IntegerVector delta,
	IntegerVector c,
  	IntegerVector nm, 
	NumericVector alpha1,
	NumericVector lambda1,
	NumericVector lambda01,
	NumericVector alpha2,
	NumericVector lambda2,
	NumericVector lambda02,
	NumericVector p,
	const double alpha00,
	const double alpha0,
	const double lambda00,
	const double alphaalpha,
	const double alphalambda,
	const double gamma0,
	const double gamma1,
	NumericVector nu,
	NumericVector ngrp,
	const double a, const double b,
	const double ymax, NumericVector tplot,
	int m, int thin);

// [[Rcpp::export]]
List compnoreg_resume(const int burnin, const int iteration,
	NumericVector t,
	IntegerVector delta,
	IntegerVector c,
  	IntegerVector nm, 
	NumericVector alpha1,
	NumericVector lambda1,
	NumericVector lambda01,
	NumericVector alpha2,
	NumericVector lambda2,
	NumericVector lambda02,
	NumericVector p,
	const double alpha00,
	const double alpha0,
	const double lambda00,
	const double alphaalpha,
	const double alphalambda,
	const double gamma0,
	const double gamma1,
	NumericVector nu,
	NumericVector ngrp,
	const double a, const double b,
	const double ymax, NumericVector tplot,
	int m, int thin, std::vector<int> emptybasket, IntegerVector allbaskets);
