#include <Rcpp.h>

// [[Rcpp::export]]
List compreg(const int burnin, const int iteration,
	NumericVector t,
	IntegerVector delta,
	NumericMatrix x,
	IntegerVector c,
   	 IntegerVector nm, 
	NumericVector alpha1,
	NumericVector lambda1,
	NumericVector lambda01,
	NumericVector alpha2,
	NumericVector lambda2,
	NumericVector lambda02,
	NumericMatrix beta1,
	NumericMatrix beta2,
	NumericVector p,
	const double alpha00,
	const double alpha0,
	const double lambda00,
	const double alphaalpha,
	const double alphalambda,
	const double gamma0,
	const double gamma1,
	NumericVector nu,
	NumericVector ngrp,
	const double a, const double b,
	const double ymax, NumericVector tplot,
	int m, int thin, double betasl,NumericVector xplot1,
        NumericVector xplot2);

// [[Rcpp::export]]
List compreg_resume(const int burnin, const int iteration,
	NumericVector t,
	IntegerVector delta,
	NumericMatrix x,
	IntegerVector c,
   	 IntegerVector nm, 
	NumericVector alpha1,
	NumericVector lambda1,
	NumericVector lambda01,
	NumericVector alpha2,
	NumericVector lambda2,
	NumericVector lambda02,
	NumericMatrix beta1,
	NumericMatrix beta2,
	NumericVector p,
	const double alpha00,
	const double alpha0,
	const double lambda00,
	const double alphaalpha,
	const double alphalambda,
	const double gamma0,
	const double gamma1,
	NumericVector nu,
	NumericVector ngrp,
	const double a, const double b,
	const double ymax, NumericVector tplot,
	int m, int thin, double betasl,NumericVector xplot1,
        NumericVector xplot2, std::vector<int> emptybasket, IntegerVector allbaskets);


// [[Rcpp::export]]
List predcompreg(NumericMatrix alpharec1,
       NumericMatrix lambdarec1,
       NumericMatrix betarec1,
       NumericMatrix alpharec2,
       NumericMatrix lambdarec2,
       NumericMatrix betarec2,
       NumericMatrix prec, NumericMatrix xplot, NumericVector tplot, double alpha);
