// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// z_which64intAndSize_DeepState_TestHarness_generation.cpp and z_which64intAndSize_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List z_which64intAndSize(IntegerVector largestSubsetSum);

TEST(FLSSS_deepstate_test,z_which64intAndSize_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector largestSubsetSum  = RcppDeepState_IntegerVector();
  std::string largestSubsetSum_t = "/home/akhila/fuzzer_packages/fuzzedpackages/FLSSS/inst/testfiles/z_which64intAndSize/libFuzzer_z_which64intAndSize/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_largestSubsetSum.qs";
  qs::c_qsave(largestSubsetSum,largestSubsetSum_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "largestSubsetSum values: "<< largestSubsetSum << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    z_which64intAndSize(largestSubsetSum);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
