// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// findweights_train_DeepState_TestHarness_generation.cpp and findweights_train_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix findweights_train(NumericMatrix trainingNodeID, NumericMatrix inbag, int ntrain, int trainIdx, int ntree);

TEST(abcrf_deepstate_test,findweights_train_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix trainingNodeID  = RcppDeepState_NumericMatrix();
  qs::c_qsave(trainingNodeID,"/home/akhila/fuzzer_packages/fuzzedpackages/abcrf/inst/testfiles/findweights_train/inputs/trainingNodeID.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "trainingNodeID values: "<< trainingNodeID << std::endl;
  NumericMatrix inbag  = RcppDeepState_NumericMatrix();
  qs::c_qsave(inbag,"/home/akhila/fuzzer_packages/fuzzedpackages/abcrf/inst/testfiles/findweights_train/inputs/inbag.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "inbag values: "<< inbag << std::endl;
  IntegerVector ntrain(1);
  ntrain[0]  = RcppDeepState_int();
  qs::c_qsave(ntrain,"/home/akhila/fuzzer_packages/fuzzedpackages/abcrf/inst/testfiles/findweights_train/inputs/ntrain.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ntrain values: "<< ntrain << std::endl;
  IntegerVector trainIdx(1);
  trainIdx[0]  = RcppDeepState_int();
  qs::c_qsave(trainIdx,"/home/akhila/fuzzer_packages/fuzzedpackages/abcrf/inst/testfiles/findweights_train/inputs/trainIdx.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "trainIdx values: "<< trainIdx << std::endl;
  IntegerVector ntree(1);
  ntree[0]  = RcppDeepState_int();
  qs::c_qsave(ntree,"/home/akhila/fuzzer_packages/fuzzedpackages/abcrf/inst/testfiles/findweights_train/inputs/ntree.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ntree values: "<< ntree << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    findweights_train(trainingNodeID,inbag,ntrain[0],trainIdx[0],ntree[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
