// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// genEpsARMAC_DeepState_TestHarness_generation.cpp and genEpsARMAC_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector genEpsARMAC(NumericVector zt, NumericVector ar, NumericVector ma);

TEST(beyondWhittle_deepstate_test,genEpsARMAC_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector zt  = RcppDeepState_NumericVector();
  qs::c_qsave(zt,"/home/akhila/fuzzer_packages/fuzzedpackages/beyondWhittle/inst/testfiles/genEpsARMAC/inputs/zt.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "zt values: "<< zt << std::endl;
  NumericVector ar  = RcppDeepState_NumericVector();
  qs::c_qsave(ar,"/home/akhila/fuzzer_packages/fuzzedpackages/beyondWhittle/inst/testfiles/genEpsARMAC/inputs/ar.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ar values: "<< ar << std::endl;
  NumericVector ma  = RcppDeepState_NumericVector();
  qs::c_qsave(ma,"/home/akhila/fuzzer_packages/fuzzedpackages/beyondWhittle/inst/testfiles/genEpsARMAC/inputs/ma.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ma values: "<< ma << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    genEpsARMAC(zt,ar,ma);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
