// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// C_check_gpstime_DeepState_TestHarness_generation.cpp and C_check_gpstime_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

int C_check_gpstime(NumericVector t, IntegerVector rn);

TEST(lidR_deepstate_test,C_check_gpstime_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector t  = RcppDeepState_NumericVector();
  qs::c_qsave(t,"/home/akhila/fuzzer_packages/fuzzedpackages/lidR/inst/testfiles/C_check_gpstime/inputs/t.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "t values: "<< t << std::endl;
  IntegerVector rn  = RcppDeepState_IntegerVector();
  qs::c_qsave(rn,"/home/akhila/fuzzer_packages/fuzzedpackages/lidR/inst/testfiles/C_check_gpstime/inputs/rn.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rn values: "<< rn << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    C_check_gpstime(t,rn);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
