# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdebug <- function(dodebug) {
    invisible(.Call(`_durmod_cdebug`, dodebug))
}

cloglik <- function(dataset, pset, control, gdiff = FALSE, dogradient = FALSE, dofisher = FALSE, onlyprobs = FALSE, onlydist = FALSE) {
    .Call(`_durmod_cloglik`, dataset, pset, control, gdiff, dogradient, dofisher, onlyprobs, onlydist)
}

genspell <- function(x1, x2, ve, vp, censor) {
    .Call(`_durmod_genspell`, x1, x2, ve, vp, censor)
}

