// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rootxylemConductanceProportions_DeepState_TestHarness_generation.cpp and rootxylemConductanceProportions_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector rootxylemConductanceProportions(NumericVector L, NumericVector V);

TEST(medfate_deepstate_test,rootxylemConductanceProportions_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector L  = RcppDeepState_NumericVector();
  qs::c_qsave(L,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/rootxylemConductanceProportions/inputs/L.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "L values: "<< L << std::endl;
  NumericVector V  = RcppDeepState_NumericVector();
  qs::c_qsave(V,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/rootxylemConductanceProportions/inputs/V.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "V values: "<< V << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rootxylemConductanceProportions(L,V);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
