// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// pejp1_ej_DeepState_TestHarness_generation.cpp and pejp1_ej_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double pejp1_ej(NumericVector ejp1Vec, NumericVector ejVec, int mu, double p);

TEST(ordinalClust_deepstate_test,pejp1_ej_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector ejp1Vec  = RcppDeepState_NumericVector();
  std::string ejp1Vec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ordinalClust/inst/testfiles/pejp1_ej/libFuzzer_pejp1_ej/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ejp1Vec.qs";
  qs::c_qsave(ejp1Vec,ejp1Vec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ejp1Vec values: "<< ejp1Vec << std::endl;
  NumericVector ejVec  = RcppDeepState_NumericVector();
  std::string ejVec_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ordinalClust/inst/testfiles/pejp1_ej/libFuzzer_pejp1_ej/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ejVec.qs";
  qs::c_qsave(ejVec,ejVec_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ejVec values: "<< ejVec << std::endl;
  IntegerVector mu(1);
  mu[0]  = RcppDeepState_int();
  std::string mu_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ordinalClust/inst/testfiles/pejp1_ej/libFuzzer_pejp1_ej/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu.qs";
  qs::c_qsave(mu,mu_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  NumericVector p(1);
  p[0]  = RcppDeepState_double();
  std::string p_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ordinalClust/inst/testfiles/pejp1_ej/libFuzzer_pejp1_ej/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_p.qs";
  qs::c_qsave(p,p_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p values: "<< p << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    pejp1_ej(ejp1Vec,ejVec,mu[0],p[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
