// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// FindIntervalCalibCPP_DeepState_TestHarness_generation.cpp and FindIntervalCalibCPP_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix FindIntervalCalibCPP(NumericMatrix w, NumericMatrix wres);

TEST(ICcalib_deepstate_test,FindIntervalCalibCPP_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix w  = RcppDeepState_NumericMatrix();
  std::string w_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ICcalib/inst/testfiles/FindIntervalCalibCPP/libFuzzer_FindIntervalCalibCPP/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_w.qs";
  qs::c_qsave(w,w_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "w values: "<< w << std::endl;
  NumericMatrix wres  = RcppDeepState_NumericMatrix();
  std::string w_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ICcalib/inst/testfiles/FindIntervalCalibCPP/libFuzzer_FindIntervalCalibCPP/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_w.qs";
  std::string wres_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ICcalib/inst/testfiles/FindIntervalCalibCPP/libFuzzer_FindIntervalCalibCPP/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_wres.qs";
  qs::c_qsave(wres,wres_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wres values: "<< wres << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    FindIntervalCalibCPP(w,wres);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
