// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// RandIndex_DeepState_TestHarness_generation.cpp and RandIndex_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List RandIndex(NumericMatrix Data);

TEST(chickn_deepstate_test,RandIndex_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix Data  = RcppDeepState_NumericMatrix();
  std::string Data_t = "/home/akhila/fuzzer_packages/fuzzedpackages/chickn/inst/testfiles/RandIndex/AFL_RandIndex/afl_inputs/" + std::to_string(t) + "_Data.qs";
  qs::c_qsave(Data,Data_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Data values: "<< Data << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    RandIndex(Data);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
