// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// appendC_DeepState_TestHarness_generation.cpp and appendC_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector appendC(IntegerVector a, IntegerVector b);

TEST(VeryLargeIntegers_deepstate_test,appendC_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector a  = RcppDeepState_IntegerVector();
  qs::c_qsave(a,"/home/akhila/fuzzer_packages/fuzzedpackages/VeryLargeIntegers/inst/testfiles/appendC/inputs/a.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a values: "<< a << std::endl;
  IntegerVector b  = RcppDeepState_IntegerVector();
  qs::c_qsave(b,"/home/akhila/fuzzer_packages/fuzzedpackages/VeryLargeIntegers/inst/testfiles/appendC/inputs/b.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    appendC(a,b);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
