// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rm_probraterfct1_DeepState_TestHarness_generation.cpp and rm_probraterfct1_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List rm_probraterfct1(Rcpp::NumericMatrix CRA, Rcpp::NumericVector DRA, Rcpp::IntegerVector dimAA, Rcpp::NumericMatrix BB, Rcpp::IntegerVector dimBB);

TEST(sirt_deepstate_test,rm_probraterfct1_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix CRA  = RcppDeepState_NumericMatrix();
  std::string CRA_t = "/home/akhila/fuzzer_packages/fuzzedpackages/sirt/inst/testfiles/rm_probraterfct1/libFuzzer_rm_probraterfct1/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_CRA.qs";
  qs::c_qsave(CRA,CRA_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "CRA values: "<< CRA << std::endl;
  NumericVector DRA  = RcppDeepState_NumericVector();
  std::string DRA_t = "/home/akhila/fuzzer_packages/fuzzedpackages/sirt/inst/testfiles/rm_probraterfct1/libFuzzer_rm_probraterfct1/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_DRA.qs";
  qs::c_qsave(DRA,DRA_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "DRA values: "<< DRA << std::endl;
  IntegerVector dimAA  = RcppDeepState_IntegerVector();
  std::string dimAA_t = "/home/akhila/fuzzer_packages/fuzzedpackages/sirt/inst/testfiles/rm_probraterfct1/libFuzzer_rm_probraterfct1/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_dimAA.qs";
  qs::c_qsave(dimAA,dimAA_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dimAA values: "<< dimAA << std::endl;
  NumericMatrix BB  = RcppDeepState_NumericMatrix();
  std::string BB_t = "/home/akhila/fuzzer_packages/fuzzedpackages/sirt/inst/testfiles/rm_probraterfct1/libFuzzer_rm_probraterfct1/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_BB.qs";
  qs::c_qsave(BB,BB_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "BB values: "<< BB << std::endl;
  IntegerVector dimBB  = RcppDeepState_IntegerVector();
  std::string dimBB_t = "/home/akhila/fuzzer_packages/fuzzedpackages/sirt/inst/testfiles/rm_probraterfct1/libFuzzer_rm_probraterfct1/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_dimBB.qs";
  qs::c_qsave(dimBB,dimBB_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dimBB values: "<< dimBB << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rm_probraterfct1(CRA,DRA,dimAA,BB,dimBB);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
