// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// multiProj_DeepState_TestHarness_generation.cpp and multiProj_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector multiProj(NumericVector beta, int j0, int j1, int deg);

TEST(mwaved_deepstate_test,multiProj_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector beta  = RcppDeepState_NumericVector();
  std::string beta_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mwaved/inst/testfiles/multiProj/libFuzzer_multiProj/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_beta.qs";
  qs::c_qsave(beta,beta_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "beta values: "<< beta << std::endl;
  IntegerVector j0(1);
  j0[0]  = RcppDeepState_int();
  std::string j0_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mwaved/inst/testfiles/multiProj/libFuzzer_multiProj/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_j0.qs";
  qs::c_qsave(j0,j0_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "j0 values: "<< j0 << std::endl;
  IntegerVector j1(1);
  j1[0]  = RcppDeepState_int();
  std::string j1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mwaved/inst/testfiles/multiProj/libFuzzer_multiProj/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_j1.qs";
  qs::c_qsave(j1,j1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "j1 values: "<< j1 << std::endl;
  IntegerVector deg(1);
  deg[0]  = RcppDeepState_int();
  std::string deg_t = "/home/akhila/fuzzer_packages/fuzzedpackages/mwaved/inst/testfiles/multiProj/libFuzzer_multiProj/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_deg.qs";
  qs::c_qsave(deg,deg_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "deg values: "<< deg << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    multiProj(beta,j0[0],j1[0],deg[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
