// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// bifiesurvey_rcpp_pathmodel_DeepState_TestHarness_generation.cpp and bifiesurvey_rcpp_pathmodel_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List bifiesurvey_rcpp_pathmodel(Rcpp::NumericMatrix datalist, Rcpp::NumericMatrix wgt1, Rcpp::NumericMatrix wgtrep, Rcpp::NumericVector vars_index, Rcpp::NumericVector fayfac, Rcpp::NumericVector NI, Rcpp::NumericVector group_index1, Rcpp::NumericVector group_values, Rcpp::NumericMatrix L, Rcpp::NumericVector L_row_index, int NL, Rcpp::NumericMatrix E, Rcpp::NumericMatrix R, Rcpp::NumericVector R_row_index, Rcpp::NumericMatrix coeff_index, int NP0, Rcpp::NumericVector unreliability);

TEST(BIFIEsurvey_deepstate_test,bifiesurvey_rcpp_pathmodel_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix datalist  = RcppDeepState_NumericMatrix();
  std::string datalist_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_datalist.qs";
  qs::c_qsave(datalist,datalist_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "datalist values: "<< datalist << std::endl;
  NumericMatrix wgt1  = RcppDeepState_NumericMatrix();
  std::string wgt1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_wgt1.qs";
  qs::c_qsave(wgt1,wgt1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wgt1 values: "<< wgt1 << std::endl;
  NumericMatrix wgtrep  = RcppDeepState_NumericMatrix();
  std::string wgtrep_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_wgtrep.qs";
  qs::c_qsave(wgtrep,wgtrep_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wgtrep values: "<< wgtrep << std::endl;
  NumericVector vars_index  = RcppDeepState_NumericVector();
  std::string vars_index_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_vars_index.qs";
  qs::c_qsave(vars_index,vars_index_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vars_index values: "<< vars_index << std::endl;
  NumericVector fayfac  = RcppDeepState_NumericVector();
  std::string fayfac_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_fayfac.qs";
  qs::c_qsave(fayfac,fayfac_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fayfac values: "<< fayfac << std::endl;
  NumericVector NI  = RcppDeepState_NumericVector();
  std::string NI_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_NI.qs";
  qs::c_qsave(NI,NI_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "NI values: "<< NI << std::endl;
  NumericVector group_index1  = RcppDeepState_NumericVector();
  std::string group_index1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_group_index1.qs";
  qs::c_qsave(group_index1,group_index1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "group_index1 values: "<< group_index1 << std::endl;
  NumericVector group_values  = RcppDeepState_NumericVector();
  std::string group_values_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_group_values.qs";
  qs::c_qsave(group_values,group_values_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "group_values values: "<< group_values << std::endl;
  NumericMatrix L  = RcppDeepState_NumericMatrix();
  std::string L_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_L.qs";
  qs::c_qsave(L,L_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "L values: "<< L << std::endl;
  NumericVector L_row_index  = RcppDeepState_NumericVector();
  std::string L_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_L.qs";
  std::string L_row_index_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_L_row_index.qs";
  qs::c_qsave(L_row_index,L_row_index_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "L_row_index values: "<< L_row_index << std::endl;
  IntegerVector NL(1);
  NL[0]  = RcppDeepState_int();
  std::string NL_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_NL.qs";
  qs::c_qsave(NL,NL_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "NL values: "<< NL << std::endl;
  NumericMatrix E  = RcppDeepState_NumericMatrix();
  std::string E_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_E.qs";
  qs::c_qsave(E,E_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "E values: "<< E << std::endl;
  NumericMatrix R  = RcppDeepState_NumericMatrix();
  std::string R_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_R.qs";
  qs::c_qsave(R,R_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "R values: "<< R << std::endl;
  NumericVector R_row_index  = RcppDeepState_NumericVector();
  std::string R_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_R.qs";
  std::string R_row_index_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_R_row_index.qs";
  qs::c_qsave(R_row_index,R_row_index_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "R_row_index values: "<< R_row_index << std::endl;
  NumericMatrix coeff_index  = RcppDeepState_NumericMatrix();
  std::string coeff_index_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_coeff_index.qs";
  qs::c_qsave(coeff_index,coeff_index_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "coeff_index values: "<< coeff_index << std::endl;
  IntegerVector NP0(1);
  NP0[0]  = RcppDeepState_int();
  std::string NP0_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_NP0.qs";
  qs::c_qsave(NP0,NP0_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "NP0 values: "<< NP0 << std::endl;
  NumericVector unreliability  = RcppDeepState_NumericVector();
  std::string unreliability_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifiesurvey_rcpp_pathmodel/libFuzzer_bifiesurvey_rcpp_pathmodel/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_unreliability.qs";
  qs::c_qsave(unreliability,unreliability_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "unreliability values: "<< unreliability << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    bifiesurvey_rcpp_pathmodel(datalist,wgt1,wgtrep,vars_index,fayfac,NI,group_index1,group_values,L,L_row_index,NL[0],E,R,R_row_index,coeff_index,NP0[0],unreliability);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
