// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// smat_DeepState_TestHarness_generation.cpp and smat_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List smat(Rcpp::NumericVector coeff);

TEST(repolr_deepstate_test,smat_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector coeff  = RcppDeepState_NumericVector();
  qs::c_qsave(coeff,"/home/akhila/fuzzer_packages/fuzzedpackages/repolr/inst/testfiles/smat/inputs/coeff.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "coeff values: "<< coeff << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    smat(coeff);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
