// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rcpp_ctap_simple_DeepState_TestHarness_generation.cpp and rcpp_ctap_simple_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector rcpp_ctap_simple(IntegerVector tapvec, const int maxslope);

TEST(psd_deepstate_test,rcpp_ctap_simple_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector tapvec  = RcppDeepState_IntegerVector();
  qs::c_qsave(tapvec,"/home/akhila/fuzzer_packages/fuzzedpackages/psd/inst/testfiles/rcpp_ctap_simple/inputs/tapvec.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tapvec values: "<< tapvec << std::endl;
  IntegerVector maxslope(1);
  maxslope[0]  = RcppDeepState_int();
  qs::c_qsave(maxslope,"/home/akhila/fuzzer_packages/fuzzedpackages/psd/inst/testfiles/rcpp_ctap_simple/inputs/maxslope.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "maxslope values: "<< maxslope << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rcpp_ctap_simple(tapvec,maxslope[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
