// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// setSITMOSeeds_DeepState_TestHarness_generation.cpp and setSITMOSeeds_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

void setSITMOSeeds(double seed);

TEST(CautiousLearning_deepstate_test,setSITMOSeeds_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector seed(1);
  seed[0]  = RcppDeepState_double();
  std::string seed_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CautiousLearning/inst/testfiles/setSITMOSeeds/libFuzzer_setSITMOSeeds/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_seed.qs";
  qs::c_qsave(seed,seed_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "seed values: "<< seed << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    setSITMOSeeds(seed[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
