// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// dcoga_approx_DeepState_TestHarness_generation.cpp and dcoga_approx_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector dcoga_approx(NumericVector x, NumericVector shape, NumericVector rate);

TEST(coga_deepstate_test,dcoga_approx_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/coga/inst/testfiles/dcoga_approx/AFL_dcoga_approx/afl_inputs/" + std::to_string(t) + "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector shape  = RcppDeepState_NumericVector();
  std::string shape_t = "/home/akhila/fuzzer_packages/fuzzedpackages/coga/inst/testfiles/dcoga_approx/AFL_dcoga_approx/afl_inputs/" + std::to_string(t) + "_shape.qs";
  qs::c_qsave(shape,shape_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "shape values: "<< shape << std::endl;
  NumericVector rate  = RcppDeepState_NumericVector();
  std::string rate_t = "/home/akhila/fuzzer_packages/fuzzedpackages/coga/inst/testfiles/dcoga_approx/AFL_dcoga_approx/afl_inputs/" + std::to_string(t) + "_rate.qs";
  qs::c_qsave(rate,rate_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rate values: "<< rate << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    dcoga_approx(x,shape,rate);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
