// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calCo_DeepState_TestHarness_generation.cpp and calCo_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector calCo(NumericMatrix prev_atoms, double length, double bAngle, double tAngle);

TEST(compas_deepstate_test,calCo_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix prev_atoms  = RcppDeepState_NumericMatrix();
  qs::c_qsave(prev_atoms,"/home/akhila/fuzzer_packages/fuzzedpackages/compas/inst/testfiles/calCo/inputs/prev_atoms.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "prev_atoms values: "<< prev_atoms << std::endl;
  NumericVector length(1);
  length[0]  = RcppDeepState_double();
  qs::c_qsave(length,"/home/akhila/fuzzer_packages/fuzzedpackages/compas/inst/testfiles/calCo/inputs/length.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "length values: "<< length << std::endl;
  NumericVector bAngle(1);
  bAngle[0]  = RcppDeepState_double();
  qs::c_qsave(bAngle,"/home/akhila/fuzzer_packages/fuzzedpackages/compas/inst/testfiles/calCo/inputs/bAngle.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bAngle values: "<< bAngle << std::endl;
  NumericVector tAngle(1);
  tAngle[0]  = RcppDeepState_double();
  qs::c_qsave(tAngle,"/home/akhila/fuzzer_packages/fuzzedpackages/compas/inst/testfiles/calCo/inputs/tAngle.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tAngle values: "<< tAngle << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calCo(prev_atoms,length[0],bAngle[0],tAngle[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
