// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// btm_biterms_text_DeepState_TestHarness_generation.cpp and btm_biterms_text_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List btm_biterms_text(Rcpp::CharacterVector x, int W, int win);

TEST(BTM_deepstate_test,btm_biterms_text_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector x  = RcppDeepState_CharacterVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BTM/inst/testfiles/btm_biterms_text/libFuzzer_btm_biterms_text/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  IntegerVector W(1);
  W[0]  = RcppDeepState_int();
  std::string W_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BTM/inst/testfiles/btm_biterms_text/libFuzzer_btm_biterms_text/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_W.qs";
  qs::c_qsave(W,W_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "W values: "<< W << std::endl;
  IntegerVector win(1);
  win[0]  = RcppDeepState_int();
  std::string win_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BTM/inst/testfiles/btm_biterms_text/libFuzzer_btm_biterms_text/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_win.qs";
  qs::c_qsave(win,win_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "win values: "<< win << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    btm_biterms_text(x,W[0],win[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
