// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// alphpow_DeepState_TestHarness_generation.cpp and alphpow_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat alphpow(double x, arma::mat mat);

TEST(repolr_deepstate_test,alphpow_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x(1);
  x[0]  = RcppDeepState_double();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/repolr/inst/testfiles/alphpow/libFuzzer_alphpow/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  std::ofstream mat_stream;
  NumericVector x(1);
  x[0]  = RcppDeepState_mat();
  mat_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/repolr/inst/testfiles/alphpow/inputs/mat");
  mat_stream << mat;
  std::cout << "mat values: "<< mat << std::endl;
  mat_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    alphpow(x[0],mat);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
