// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rowmins2_bundle_C_DeepState_TestHarness_generation.cpp and rowmins2_bundle_C_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericMatrix rowmins2_bundle_C(Rcpp::NumericMatrix m1, Rcpp::NumericVector v1);

TEST(sirt_deepstate_test,rowmins2_bundle_C_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix m1  = RcppDeepState_NumericMatrix();
  std::string m1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/sirt/inst/testfiles/rowmins2_bundle_C/libFuzzer_rowmins2_bundle_C/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_m1.qs";
  qs::c_qsave(m1,m1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m1 values: "<< m1 << std::endl;
  NumericVector v1  = RcppDeepState_NumericVector();
  std::string v1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/sirt/inst/testfiles/rowmins2_bundle_C/libFuzzer_rowmins2_bundle_C/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_v1.qs";
  qs::c_qsave(v1,v1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "v1 values: "<< v1 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rowmins2_bundle_C(m1,v1);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
