// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// fineRootHalfDistance_DeepState_TestHarness_generation.cpp and fineRootHalfDistance_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double fineRootHalfDistance(double rootLengthDensity);

TEST(medfate_deepstate_test,fineRootHalfDistance_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector rootLengthDensity(1);
  rootLengthDensity[0]  = RcppDeepState_double();
  std::string rootLengthDensity_t = "/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/fineRootHalfDistance/libFuzzer_fineRootHalfDistance/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rootLengthDensity.qs";
  qs::c_qsave(rootLengthDensity,rootLengthDensity_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rootLengthDensity values: "<< rootLengthDensity << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    fineRootHalfDistance(rootLengthDensity[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
