// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// myrpois__DeepState_TestHarness_generation.cpp and myrpois__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector myrpois_(NumericVector means, int seed);

TEST(detrendr_deepstate_test,myrpois__test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector means  = RcppDeepState_NumericVector();
  qs::c_qsave(means,"/home/akhila/fuzzer_packages/fuzzedpackages/detrendr/inst/testfiles/myrpois_/inputs/means.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "means values: "<< means << std::endl;
  IntegerVector seed(1);
  seed[0]  = RcppDeepState_int();
  qs::c_qsave(seed,"/home/akhila/fuzzer_packages/fuzzedpackages/detrendr/inst/testfiles/myrpois_/inputs/seed.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "seed values: "<< seed << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    myrpois_(means,seed[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
