// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// psrkg_DeepState_TestHarness_generation.cpp and psrkg_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double psrkg(int srk, IntegerVector Score);

TEST(clusrank_deepstate_test,psrkg_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector srk(1);
  srk[0]  = RcppDeepState_int();
  qs::c_qsave(srk,"/home/akhila/fuzzer_packages/fuzzedpackages/clusrank/inst/testfiles/psrkg/inputs/srk.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "srk values: "<< srk << std::endl;
  IntegerVector Score  = RcppDeepState_IntegerVector();
  qs::c_qsave(Score,"/home/akhila/fuzzer_packages/fuzzedpackages/clusrank/inst/testfiles/psrkg/inputs/Score.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Score values: "<< Score << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    psrkg(srk[0],Score);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
