// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// roundc_DeepState_TestHarness_generation.cpp and roundc_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector roundc(NumericVector x, int digit);

TEST(lidR_deepstate_test,roundc_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/lidR/inst/testfiles/roundc/libFuzzer_roundc/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  IntegerVector digit(1);
  digit[0]  = RcppDeepState_int();
  std::string digit_t = "/home/akhila/fuzzer_packages/fuzzedpackages/lidR/inst/testfiles/roundc/libFuzzer_roundc/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_digit.qs";
  qs::c_qsave(digit,digit_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "digit values: "<< digit << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    roundc(x,digit[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
