// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// max_heapify_DeepState_TestHarness_generation.cpp and max_heapify_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix max_heapify(NumericMatrix data, int index, int num_data);

TEST(DCEM_deepstate_test,max_heapify_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix data  = RcppDeepState_NumericMatrix();
  qs::c_qsave(data,"/home/akhila/fuzzer_packages/fuzzedpackages/DCEM/inst/testfiles/max_heapify/inputs/data.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "data values: "<< data << std::endl;
  IntegerVector index(1);
  index[0]  = RcppDeepState_int();
  qs::c_qsave(index,"/home/akhila/fuzzer_packages/fuzzedpackages/DCEM/inst/testfiles/max_heapify/inputs/index.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "index values: "<< index << std::endl;
  IntegerVector num_data(1);
  num_data[0]  = RcppDeepState_int();
  qs::c_qsave(num_data,"/home/akhila/fuzzer_packages/fuzzedpackages/DCEM/inst/testfiles/max_heapify/inputs/num_data.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "num_data values: "<< num_data << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    max_heapify(data,index[0],num_data[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
