// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// CPL_hex_to_raw_DeepState_TestHarness_generation.cpp and CPL_hex_to_raw_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List CPL_hex_to_raw(Rcpp::CharacterVector cx);

TEST(sf_deepstate_test,CPL_hex_to_raw_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  CharacterVector cx  = RcppDeepState_CharacterVector();
  qs::c_qsave(cx,"/home/akhila/fuzzer_packages/fuzzedpackages/sf/inst/testfiles/CPL_hex_to_raw/inputs/cx.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cx values: "<< cx << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    CPL_hex_to_raw(cx);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
