// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// bifie_test_univar_DeepState_TestHarness_generation.cpp and bifie_test_univar_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List bifie_test_univar(Rcpp::NumericMatrix mean1M, Rcpp::NumericMatrix sd1M, Rcpp::NumericMatrix sumweightM, int GG, Rcpp::NumericVector group_values, Rcpp::NumericMatrix mean1repM, Rcpp::NumericMatrix sd1repM, Rcpp::NumericMatrix sumweightrepM, Rcpp::NumericVector fayfac);

TEST(BIFIEsurvey_deepstate_test,bifie_test_univar_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix mean1M  = RcppDeepState_NumericMatrix();
  qs::c_qsave(mean1M,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifie_test_univar/inputs/mean1M.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mean1M values: "<< mean1M << std::endl;
  NumericMatrix sd1M  = RcppDeepState_NumericMatrix();
  qs::c_qsave(sd1M,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifie_test_univar/inputs/sd1M.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sd1M values: "<< sd1M << std::endl;
  NumericMatrix sumweightM  = RcppDeepState_NumericMatrix();
  qs::c_qsave(sumweightM,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifie_test_univar/inputs/sumweightM.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sumweightM values: "<< sumweightM << std::endl;
  IntegerVector GG(1);
  GG[0]  = RcppDeepState_int();
  qs::c_qsave(GG,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifie_test_univar/inputs/GG.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "GG values: "<< GG << std::endl;
  NumericVector group_values  = RcppDeepState_NumericVector();
  qs::c_qsave(group_values,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifie_test_univar/inputs/group_values.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "group_values values: "<< group_values << std::endl;
  NumericMatrix mean1repM  = RcppDeepState_NumericMatrix();
  qs::c_qsave(mean1repM,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifie_test_univar/inputs/mean1repM.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mean1repM values: "<< mean1repM << std::endl;
  NumericMatrix sd1repM  = RcppDeepState_NumericMatrix();
  qs::c_qsave(sd1repM,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifie_test_univar/inputs/sd1repM.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sd1repM values: "<< sd1repM << std::endl;
  NumericMatrix sumweightrepM  = RcppDeepState_NumericMatrix();
  qs::c_qsave(sumweightrepM,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifie_test_univar/inputs/sumweightrepM.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sumweightrepM values: "<< sumweightrepM << std::endl;
  NumericVector fayfac  = RcppDeepState_NumericVector();
  qs::c_qsave(fayfac,"/home/akhila/fuzzer_packages/fuzzedpackages/BIFIEsurvey/inst/testfiles/bifie_test_univar/inputs/fayfac.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fayfac values: "<< fayfac << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    bifie_test_univar(mean1M,sd1M,sumweightM,GG[0],group_values,mean1repM,sd1repM,sumweightrepM,fayfac);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
