// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ACPS_DeepState_TestHarness_generation.cpp and ACPS_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List ACPS(IntegerVector x, int nbs, int reference);

TEST(OTclust_deepstate_test,ACPS_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector x  = RcppDeepState_IntegerVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/OTclust/inst/testfiles/ACPS/libFuzzer_ACPS/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  IntegerVector nbs(1);
  nbs[0]  = RcppDeepState_int();
  std::string nbs_t = "/home/akhila/fuzzer_packages/fuzzedpackages/OTclust/inst/testfiles/ACPS/libFuzzer_ACPS/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nbs.qs";
  qs::c_qsave(nbs,nbs_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nbs values: "<< nbs << std::endl;
  IntegerVector reference(1);
  reference[0]  = RcppDeepState_int();
  std::string reference_t = "/home/akhila/fuzzer_packages/fuzzedpackages/OTclust/inst/testfiles/ACPS/libFuzzer_ACPS/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_reference.qs";
  qs::c_qsave(reference,reference_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "reference values: "<< reference << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ACPS(x,nbs[0],reference[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
