// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// qgompertz_ssd_DeepState_TestHarness_generation.cpp and qgompertz_ssd_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double qgompertz_ssd(double p, double location, double shape);

TEST(ssdtools_deepstate_test,qgompertz_ssd_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector p(1);
  p[0]  = RcppDeepState_double();
  std::string p_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ssdtools/inst/testfiles/qgompertz_ssd/libFuzzer_qgompertz_ssd/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_p.qs";
  qs::c_qsave(p,p_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p values: "<< p << std::endl;
  NumericVector location(1);
  location[0]  = RcppDeepState_double();
  std::string location_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ssdtools/inst/testfiles/qgompertz_ssd/libFuzzer_qgompertz_ssd/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_location.qs";
  qs::c_qsave(location,location_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "location values: "<< location << std::endl;
  NumericVector shape(1);
  shape[0]  = RcppDeepState_double();
  std::string shape_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ssdtools/inst/testfiles/qgompertz_ssd/libFuzzer_qgompertz_ssd/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_shape.qs";
  qs::c_qsave(shape,shape_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "shape values: "<< shape << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    qgompertz_ssd(p[0],location[0],shape[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
