# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pdist <- function(x, D) {
    .Call('_dcov_pdist', PACKAGE = 'dcov', x, D)
}

Ucenter <- function(D) {
    .Call('_dcov_Ucenter', PACKAGE = 'dcov', D)
}

Vcenter <- function(D) {
    .Call('_dcov_Vcenter', PACKAGE = 'dcov', D)
}

centering <- function(D, type = "V") {
    .Call('_dcov_centering', PACKAGE = 'dcov', D, type)
}

centering_from_data <- function(x, D, type = "V") {
    .Call('_dcov_centering_from_data', PACKAGE = 'dcov', x, D, type)
}

dcov <- function(x, y, type = "V") {
    .Call('_dcov_dcov', PACKAGE = 'dcov', x, y, type)
}

dcor <- function(x, y, type) {
    .Call('_dcov_dcor', PACKAGE = 'dcov', x, y, type)
}

dcov1v1 <- function(x, y, type = "V") {
    .Call('_dcov_dcov1v1', PACKAGE = 'dcov', x, y, type)
}

dcor1v1 <- function(x, y, type = "V") {
    .Call('_dcov_dcor1v1', PACKAGE = 'dcov', x, y, type)
}

mdcov <- function(y, x, type = "V") {
    .Call('_dcov_mdcov', PACKAGE = 'dcov', y, x, type)
}

mdcor <- function(y, x, type = "V") {
    .Call('_dcov_mdcor', PACKAGE = 'dcov', y, x, type)
}

pcovCpp <- function(x, y) {
    .Call('_dcov_pcovCpp', PACKAGE = 'dcov', x, y)
}

pdcov <- function(x, y, z, type = "V") {
    .Call('_dcov_pdcov', PACKAGE = 'dcov', x, y, z, type)
}

pdcor <- function(x, y, z, type = "V") {
    .Call('_dcov_pdcor', PACKAGE = 'dcov', x, y, z, type)
}

pdcov1v1v1 <- function(x, y, z, type) {
    .Call('_dcov_pdcov1v1v1', PACKAGE = 'dcov', x, y, z, type)
}

pdcor1v1v1 <- function(x, y, z, type) {
    .Call('_dcov_pdcor1v1v1', PACKAGE = 'dcov', x, y, z, type)
}

dcor_test <- function(x, y, R, type = "V") {
    .Call('_dcov_dcor_test', PACKAGE = 'dcov', x, y, R, type)
}

pdcor_test <- function(x, y, z, R, type = "U") {
    .Call('_dcov_pdcor_test', PACKAGE = 'dcov', x, y, z, R, type)
}

