// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// select_line_connection_DeepState_TestHarness_generation.cpp and select_line_connection_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector select_line_connection(NumericVector p1, NumericVector b);

TEST(ggrepel_deepstate_test,select_line_connection_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector p1  = RcppDeepState_NumericVector();
  qs::c_qsave(p1,"/home/akhila/fuzzer_packages/fuzzedpackages/ggrepel/inst/testfiles/select_line_connection/inputs/p1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p1 values: "<< p1 << std::endl;
  NumericVector b  = RcppDeepState_NumericVector();
  qs::c_qsave(b,"/home/akhila/fuzzer_packages/fuzzedpackages/ggrepel/inst/testfiles/select_line_connection/inputs/b.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    select_line_connection(p1,b);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
