// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// multi_across_fip_DeepState_TestHarness_generation.cpp and multi_across_fip_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List multi_across_fip(NumericMatrix X, int M, double min_draw, NumericVector tau, NumericVector p, NumericVector epp, double Ts);

TEST(wbsts_deepstate_test,multi_across_fip_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix X  = RcppDeepState_NumericMatrix();
  std::string X_t = "/home/akhila/fuzzer_packages/fuzzedpackages/wbsts/inst/testfiles/multi_across_fip/AFL_multi_across_fip/afl_inputs/" + std::to_string(t) + "_X.qs";
  qs::c_qsave(X,X_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "X values: "<< X << std::endl;
  IntegerVector M(1);
  M[0]  = RcppDeepState_int();
  std::string M_t = "/home/akhila/fuzzer_packages/fuzzedpackages/wbsts/inst/testfiles/multi_across_fip/AFL_multi_across_fip/afl_inputs/" + std::to_string(t) + "_M.qs";
  qs::c_qsave(M,M_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "M values: "<< M << std::endl;
  NumericVector min_draw(1);
  min_draw[0]  = RcppDeepState_double();
  std::string min_draw_t = "/home/akhila/fuzzer_packages/fuzzedpackages/wbsts/inst/testfiles/multi_across_fip/AFL_multi_across_fip/afl_inputs/" + std::to_string(t) + "_min_draw.qs";
  qs::c_qsave(min_draw,min_draw_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "min_draw values: "<< min_draw << std::endl;
  NumericVector tau  = RcppDeepState_NumericVector();
  std::string tau_t = "/home/akhila/fuzzer_packages/fuzzedpackages/wbsts/inst/testfiles/multi_across_fip/AFL_multi_across_fip/afl_inputs/" + std::to_string(t) + "_tau.qs";
  qs::c_qsave(tau,tau_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tau values: "<< tau << std::endl;
  NumericVector p  = RcppDeepState_NumericVector();
  std::string p_t = "/home/akhila/fuzzer_packages/fuzzedpackages/wbsts/inst/testfiles/multi_across_fip/AFL_multi_across_fip/afl_inputs/" + std::to_string(t) + "_p.qs";
  qs::c_qsave(p,p_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p values: "<< p << std::endl;
  NumericVector epp  = RcppDeepState_NumericVector();
  std::string epp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/wbsts/inst/testfiles/multi_across_fip/AFL_multi_across_fip/afl_inputs/" + std::to_string(t) + "_epp.qs";
  qs::c_qsave(epp,epp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "epp values: "<< epp << std::endl;
  NumericVector Ts(1);
  Ts[0]  = RcppDeepState_double();
  std::string Ts_t = "/home/akhila/fuzzer_packages/fuzzedpackages/wbsts/inst/testfiles/multi_across_fip/AFL_multi_across_fip/afl_inputs/" + std::to_string(t) + "_Ts.qs";
  qs::c_qsave(Ts,Ts_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Ts values: "<< Ts << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    multi_across_fip(X,M[0],min_draw[0],tau,p,epp,Ts[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
