// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cxxdeclust_DeepState_TestHarness_generation.cpp and cxxdeclust_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List cxxdeclust(NumericVector param, NumericMatrix revents, NumericMatrix rpoly, NumericVector bwd, NumericVector tperiod, int ndiv);

TEST(ETAS_deepstate_test,cxxdeclust_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector param  = RcppDeepState_NumericVector();
  std::string param_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ETAS/inst/testfiles/cxxdeclust/AFL_cxxdeclust/afl_inputs/" + std::to_string(t) + "_param.qs";
  qs::c_qsave(param,param_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "param values: "<< param << std::endl;
  NumericMatrix revents  = RcppDeepState_NumericMatrix();
  std::string revents_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ETAS/inst/testfiles/cxxdeclust/AFL_cxxdeclust/afl_inputs/" + std::to_string(t) + "_revents.qs";
  qs::c_qsave(revents,revents_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "revents values: "<< revents << std::endl;
  NumericMatrix rpoly  = RcppDeepState_NumericMatrix();
  std::string rpoly_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ETAS/inst/testfiles/cxxdeclust/AFL_cxxdeclust/afl_inputs/" + std::to_string(t) + "_rpoly.qs";
  qs::c_qsave(rpoly,rpoly_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rpoly values: "<< rpoly << std::endl;
  NumericVector bwd  = RcppDeepState_NumericVector();
  std::string bwd_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ETAS/inst/testfiles/cxxdeclust/AFL_cxxdeclust/afl_inputs/" + std::to_string(t) + "_bwd.qs";
  qs::c_qsave(bwd,bwd_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "bwd values: "<< bwd << std::endl;
  NumericVector tperiod  = RcppDeepState_NumericVector();
  std::string tperiod_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ETAS/inst/testfiles/cxxdeclust/AFL_cxxdeclust/afl_inputs/" + std::to_string(t) + "_tperiod.qs";
  qs::c_qsave(tperiod,tperiod_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tperiod values: "<< tperiod << std::endl;
  IntegerVector ndiv(1);
  ndiv[0]  = RcppDeepState_int();
  std::string ndiv_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ETAS/inst/testfiles/cxxdeclust/AFL_cxxdeclust/afl_inputs/" + std::to_string(t) + "_ndiv.qs";
  qs::c_qsave(ndiv,ndiv_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ndiv values: "<< ndiv << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cxxdeclust(param,revents,rpoly,bwd,tperiod,ndiv[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
