// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// shingle_ngrams_DeepState_TestHarness_generation.cpp and shingle_ngrams_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

CharacterVector shingle_ngrams(CharacterVector words, int n);

TEST(textreuse_deepstate_test,shingle_ngrams_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector words  = RcppDeepState_CharacterVector();
  std::string words_t = "/home/akhila/fuzzer_packages/fuzzedpackages/textreuse/inst/testfiles/shingle_ngrams/libFuzzer_shingle_ngrams/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_words.qs";
  qs::c_qsave(words,words_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "words values: "<< words << std::endl;
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/textreuse/inst/testfiles/shingle_ngrams/libFuzzer_shingle_ngrams/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    shingle_ngrams(words,n[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
