// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// sp_hfilter_DeepState_TestHarness_generation.cpp and sp_hfilter_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::vec sp_hfilter(int jscale);

TEST(wv_deepstate_test,sp_hfilter_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector jscale(1);
  jscale[0]  = RcppDeepState_int();
  std::string jscale_t = "/home/akhila/fuzzer_packages/fuzzedpackages/wv/inst/testfiles/sp_hfilter/libFuzzer_sp_hfilter/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_jscale.qs";
  qs::c_qsave(jscale,jscale_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "jscale values: "<< jscale << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    sp_hfilter(jscale[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
