// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// kmnsw_DeepState_TestHarness_generation.cpp and kmnsw_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List kmnsw(Rcpp::NumericMatrix a_R, Rcpp::NumericMatrix c_R, Rcpp::NumericVector wh_R, int k, int iter);

TEST(stream_deepstate_test,kmnsw_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix a_R  = RcppDeepState_NumericMatrix();
  std::string a_R_t = "/home/akhila/fuzzer_packages/fuzzedpackages/stream/inst/testfiles/kmnsw/AFL_kmnsw/afl_inputs/" + std::to_string(t) + "_a_R.qs";
  qs::c_qsave(a_R,a_R_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a_R values: "<< a_R << std::endl;
  NumericMatrix c_R  = RcppDeepState_NumericMatrix();
  std::string c_R_t = "/home/akhila/fuzzer_packages/fuzzedpackages/stream/inst/testfiles/kmnsw/AFL_kmnsw/afl_inputs/" + std::to_string(t) + "_c_R.qs";
  qs::c_qsave(c_R,c_R_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "c_R values: "<< c_R << std::endl;
  NumericVector wh_R  = RcppDeepState_NumericVector();
  std::string wh_R_t = "/home/akhila/fuzzer_packages/fuzzedpackages/stream/inst/testfiles/kmnsw/AFL_kmnsw/afl_inputs/" + std::to_string(t) + "_wh_R.qs";
  qs::c_qsave(wh_R,wh_R_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "wh_R values: "<< wh_R << std::endl;
  IntegerVector k(1);
  k[0]  = RcppDeepState_int();
  std::string k_t = "/home/akhila/fuzzer_packages/fuzzedpackages/stream/inst/testfiles/kmnsw/AFL_kmnsw/afl_inputs/" + std::to_string(t) + "_k.qs";
  qs::c_qsave(k,k_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "k values: "<< k << std::endl;
  IntegerVector iter(1);
  iter[0]  = RcppDeepState_int();
  std::string iter_t = "/home/akhila/fuzzer_packages/fuzzedpackages/stream/inst/testfiles/kmnsw/AFL_kmnsw/afl_inputs/" + std::to_string(t) + "_iter.qs";
  qs::c_qsave(iter,iter_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "iter values: "<< iter << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    kmnsw(a_R,c_R,wh_R,k[0],iter[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
