// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Rcpporder_DeepState_TestHarness_generation.cpp and Rcpporder_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat Rcpporder(int k, arma::mat W);

TEST(MomTrunc_deepstate_test,Rcpporder_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector k(1);
  k[0]  = RcppDeepState_int();
  std::string k_t = "/home/akhila/fuzzer_packages/fuzzedpackages/MomTrunc/inst/testfiles/Rcpporder/AFL_Rcpporder/afl_inputs/" + std::to_string(t) + "_k.qs";
  qs::c_qsave(k,k_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "k values: "<< k << std::endl;
  std::ofstream W_stream;
  IntegerVector k(1);
  k[0]  = RcppDeepState_mat();
  W_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/MomTrunc/inst/testfiles/Rcpporder/inputs/W");
  W_stream << W;
  std::cout << "W values: "<< W << std::endl;
  W_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    Rcpporder(k[0],W);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
