// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// qform_ST_DeepState_TestHarness_generation.cpp and qform_ST_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double qform_ST(NumericMatrix Qspace, NumericMatrix Qtime, NumericVector phi, int nsites);

TEST(CARBayesST_deepstate_test,qform_ST_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix Qspace  = RcppDeepState_NumericMatrix();
  std::string Qspace_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/qform_ST/AFL_qform_ST/afl_inputs/" + std::to_string(t) + "_Qspace.qs";
  qs::c_qsave(Qspace,Qspace_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Qspace values: "<< Qspace << std::endl;
  NumericMatrix Qtime  = RcppDeepState_NumericMatrix();
  std::string Qtime_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/qform_ST/AFL_qform_ST/afl_inputs/" + std::to_string(t) + "_Qtime.qs";
  qs::c_qsave(Qtime,Qtime_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Qtime values: "<< Qtime << std::endl;
  NumericVector phi  = RcppDeepState_NumericVector();
  std::string phi_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/qform_ST/AFL_qform_ST/afl_inputs/" + std::to_string(t) + "_phi.qs";
  qs::c_qsave(phi,phi_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "phi values: "<< phi << std::endl;
  IntegerVector nsites(1);
  nsites[0]  = RcppDeepState_int();
  std::string nsites_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/qform_ST/AFL_qform_ST/afl_inputs/" + std::to_string(t) + "_nsites.qs";
  qs::c_qsave(nsites,nsites_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nsites values: "<< nsites << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    qform_ST(Qspace,Qtime,phi,nsites[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
