# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tesseract_config <- function() {
    .Call('_tesseract_tesseract_config', PACKAGE = 'tesseract')
}

tesseract_engine_internal <- function(datapath, language, confpaths, opt_names, opt_values) {
    .Call('_tesseract_tesseract_engine_internal', PACKAGE = 'tesseract', datapath, language, confpaths, opt_names, opt_values)
}

tesseract_engine_set_variable <- function(ptr, name, value) {
    .Call('_tesseract_tesseract_engine_set_variable', PACKAGE = 'tesseract', ptr, name, value)
}

validate_params <- function(params) {
    .Call('_tesseract_validate_params', PACKAGE = 'tesseract', params)
}

engine_info_internal <- function(ptr) {
    .Call('_tesseract_engine_info_internal', PACKAGE = 'tesseract', ptr)
}

print_params <- function(filename) {
    .Call('_tesseract_print_params', PACKAGE = 'tesseract', filename)
}

get_param_values <- function(ptr, params) {
    .Call('_tesseract_get_param_values', PACKAGE = 'tesseract', ptr, params)
}

ocr_raw <- function(input, ptr, HOCR = FALSE) {
    .Call('_tesseract_ocr_raw', PACKAGE = 'tesseract', input, ptr, HOCR)
}

ocr_file <- function(file, ptr, HOCR = FALSE) {
    .Call('_tesseract_ocr_file', PACKAGE = 'tesseract', file, ptr, HOCR)
}

ocr_raw_data <- function(input, ptr) {
    .Call('_tesseract_ocr_raw_data', PACKAGE = 'tesseract', input, ptr)
}

ocr_file_data <- function(file, ptr) {
    .Call('_tesseract_ocr_file_data', PACKAGE = 'tesseract', file, ptr)
}

