// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ema_weights_DeepState_TestHarness_generation.cpp and ema_weights_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

std::vector<double> ema_weights(double len);

TEST(cycleRtools_deepstate_test,ema_weights_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector len(1);
  len[0]  = RcppDeepState_double();
  qs::c_qsave(len,"/home/akhila/fuzzer_packages/fuzzedpackages/cycleRtools/inst/testfiles/ema_weights/inputs/len.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "len values: "<< len << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ema_weights(len[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
