// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rvm
arma::vec rvm(int n, double mu, double k);
RcppExport SEXP _CircularDDM_rvm(SEXP nSEXP, SEXP muSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(rvm(n, mu, k));
    return rcpp_result_gen;
END_RCPP
}
// besselzero
arma::vec besselzero(double nu, int k, int kind);
RcppExport SEXP _CircularDDM_besselzero(SEXP nuSEXP, SEXP kSEXP, SEXP kindSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type kind(kindSEXP);
    rcpp_result_gen = Rcpp::wrap(besselzero(nu, k, kind));
    return rcpp_result_gen;
END_RCPP
}
// logLik_resp
arma::vec logLik_resp(arma::mat x, arma::vec pVec);
RcppExport SEXP _CircularDDM_logLik_resp(SEXP xSEXP, SEXP pVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pVec(pVecSEXP);
    rcpp_result_gen = Rcpp::wrap(logLik_resp(x, pVec));
    return rcpp_result_gen;
END_RCPP
}
// logLik_dt
arma::vec logLik_dt(arma::mat x, arma::vec pVec, int k);
RcppExport SEXP _CircularDDM_logLik_dt(SEXP xSEXP, SEXP pVecSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pVec(pVecSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(logLik_dt(x, pVec, k));
    return rcpp_result_gen;
END_RCPP
}
// dcddm
arma::vec dcddm(arma::mat x, arma::vec pVec, int k);
RcppExport SEXP _CircularDDM_dcddm(SEXP xSEXP, SEXP pVecSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pVec(pVecSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(dcddm(x, pVec, k));
    return rcpp_result_gen;
END_RCPP
}
// rcddm
arma::mat rcddm(int n, arma::vec pVec, double p);
RcppExport SEXP _CircularDDM_rcddm(SEXP nSEXP, SEXP pVecSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pVec(pVecSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(rcddm(n, pVec, p));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CircularDDM_rvm", (DL_FUNC) &_CircularDDM_rvm, 3},
    {"_CircularDDM_besselzero", (DL_FUNC) &_CircularDDM_besselzero, 3},
    {"_CircularDDM_logLik_resp", (DL_FUNC) &_CircularDDM_logLik_resp, 2},
    {"_CircularDDM_logLik_dt", (DL_FUNC) &_CircularDDM_logLik_dt, 3},
    {"_CircularDDM_dcddm", (DL_FUNC) &_CircularDDM_dcddm, 3},
    {"_CircularDDM_rcddm", (DL_FUNC) &_CircularDDM_rcddm, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_CircularDDM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
