// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// densityMixture_DeepState_TestHarness_generation.cpp and densityMixture_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector densityMixture(NumericVector weights, NumericMatrix densities);

TEST(beyondWhittle_deepstate_test,densityMixture_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector weights  = RcppDeepState_NumericVector();
  qs::c_qsave(weights,"/home/akhila/fuzzer_packages/fuzzedpackages/beyondWhittle/inst/testfiles/densityMixture/inputs/weights.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "weights values: "<< weights << std::endl;
  NumericMatrix densities  = RcppDeepState_NumericMatrix();
  qs::c_qsave(densities,"/home/akhila/fuzzer_packages/fuzzedpackages/beyondWhittle/inst/testfiles/densityMixture/inputs/densities.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "densities values: "<< densities << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    densityMixture(weights,densities);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
