// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// zone_index__DeepState_TestHarness_generation.cpp and zone_index__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

std::vector<double> zone_index_(NumericVector x, NumericVector zb);

TEST(cycleRtools_deepstate_test,zone_index__test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/cycleRtools/inst/testfiles/zone_index_/libFuzzer_zone_index_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector zb  = RcppDeepState_NumericVector();
  std::string zb_t = "/home/akhila/fuzzer_packages/fuzzedpackages/cycleRtools/inst/testfiles/zone_index_/libFuzzer_zone_index_/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_zb.qs";
  qs::c_qsave(zb,zb_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "zb values: "<< zb << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    zone_index_(x,zb);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
