// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// referenceConductivityHeightFactor_DeepState_TestHarness_generation.cpp and referenceConductivityHeightFactor_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double referenceConductivityHeightFactor(double refheight, double height);

TEST(medfate_deepstate_test,referenceConductivityHeightFactor_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector refheight(1);
  refheight[0]  = RcppDeepState_double();
  std::string refheight_t = "/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/referenceConductivityHeightFactor/libFuzzer_referenceConductivityHeightFactor/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_refheight.qs";
  qs::c_qsave(refheight,refheight_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "refheight values: "<< refheight << std::endl;
  NumericVector height(1);
  height[0]  = RcppDeepState_double();
  std::string height_t = "/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/referenceConductivityHeightFactor/libFuzzer_referenceConductivityHeightFactor/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_height.qs";
  qs::c_qsave(height,height_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "height values: "<< height << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    referenceConductivityHeightFactor(refheight[0],height[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
