// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Timeout__new_DeepState_TestHarness_generation.cpp and Timeout__new_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

SEXP Timeout__new(double delay);

TEST(simmer_deepstate_test,Timeout__new_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector delay(1);
  delay[0]  = RcppDeepState_double();
  qs::c_qsave(delay,"/home/akhila/fuzzer_packages/fuzzedpackages/simmer/inst/testfiles/Timeout__new/inputs/delay.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "delay values: "<< delay << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Timeout__new(delay[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
