// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ECapacitance_DeepState_TestHarness_generation.cpp and ECapacitance_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double ECapacitance(double psi, double psiPrev, double PLCprev, double V, double fapo, double c, double d, double pi0, double eps, double timestep);

TEST(medfate_deepstate_test,ECapacitance_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector psi(1);
  psi[0]  = RcppDeepState_double();
  qs::c_qsave(psi,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECapacitance/inputs/psi.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "psi values: "<< psi << std::endl;
  NumericVector psiPrev(1);
  psiPrev[0]  = RcppDeepState_double();
  qs::c_qsave(psiPrev,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECapacitance/inputs/psiPrev.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "psiPrev values: "<< psiPrev << std::endl;
  NumericVector PLCprev(1);
  PLCprev[0]  = RcppDeepState_double();
  qs::c_qsave(PLCprev,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECapacitance/inputs/PLCprev.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "PLCprev values: "<< PLCprev << std::endl;
  NumericVector V(1);
  V[0]  = RcppDeepState_double();
  qs::c_qsave(V,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECapacitance/inputs/V.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "V values: "<< V << std::endl;
  NumericVector fapo(1);
  fapo[0]  = RcppDeepState_double();
  qs::c_qsave(fapo,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECapacitance/inputs/fapo.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fapo values: "<< fapo << std::endl;
  NumericVector c(1);
  c[0]  = RcppDeepState_double();
  qs::c_qsave(c,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECapacitance/inputs/c.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "c values: "<< c << std::endl;
  NumericVector d(1);
  d[0]  = RcppDeepState_double();
  qs::c_qsave(d,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECapacitance/inputs/d.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "d values: "<< d << std::endl;
  NumericVector pi0(1);
  pi0[0]  = RcppDeepState_double();
  qs::c_qsave(pi0,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECapacitance/inputs/pi0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pi0 values: "<< pi0 << std::endl;
  NumericVector eps(1);
  eps[0]  = RcppDeepState_double();
  qs::c_qsave(eps,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECapacitance/inputs/eps.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "eps values: "<< eps << std::endl;
  NumericVector timestep(1);
  timestep[0]  = RcppDeepState_double();
  qs::c_qsave(timestep,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECapacitance/inputs/timestep.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "timestep values: "<< timestep << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ECapacitance(psi[0],psiPrev[0],PLCprev[0],V[0],fapo[0],c[0],d[0],pi0[0],eps[0],timestep[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
