// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// tam_rcpp_mml_mfr_gresp_extend_DeepState_TestHarness_generation.cpp and tam_rcpp_mml_mfr_gresp_extend_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericMatrix tam_rcpp_mml_mfr_gresp_extend(Rcpp::NumericMatrix gresp, Rcpp::NumericVector xstep);

TEST(TAM_deepstate_test,tam_rcpp_mml_mfr_gresp_extend_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix gresp  = RcppDeepState_NumericMatrix();
  qs::c_qsave(gresp,"/home/akhila/fuzzer_packages/fuzzedpackages/TAM/inst/testfiles/tam_rcpp_mml_mfr_gresp_extend/inputs/gresp.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "gresp values: "<< gresp << std::endl;
  NumericVector xstep  = RcppDeepState_NumericVector();
  qs::c_qsave(xstep,"/home/akhila/fuzzer_packages/fuzzedpackages/TAM/inst/testfiles/tam_rcpp_mml_mfr_gresp_extend/inputs/xstep.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xstep values: "<< xstep << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    tam_rcpp_mml_mfr_gresp_extend(gresp,xstep);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
