// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// psiCrit_DeepState_TestHarness_generation.cpp and psiCrit_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double psiCrit(double c, double d, double pCrit);

TEST(medfate_deepstate_test,psiCrit_test){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector c(1);
  c[0]  = RcppDeepState_double();
  std::string c_t = "/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/psiCrit/libFuzzer_psiCrit/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_c.qs";
  qs::c_qsave(c,c_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "c values: "<< c << std::endl;
  NumericVector d(1);
  d[0]  = RcppDeepState_double();
  std::string d_t = "/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/psiCrit/libFuzzer_psiCrit/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_d.qs";
  qs::c_qsave(d,d_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "d values: "<< d << std::endl;
  NumericVector pCrit(1);
  pCrit[0]  = RcppDeepState_double();
  std::string pCrit_t = "/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/psiCrit/libFuzzer_psiCrit/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_pCrit.qs";
  qs::c_qsave(pCrit,pCrit_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pCrit values: "<< pCrit << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    psiCrit(c[0],d[0],pCrit[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
