// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// tau2quadform_DeepState_TestHarness_generation.cpp and tau2quadform_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector tau2quadform(NumericMatrix Wtriplet, NumericVector Wtripletsum, const int n_triplet, const int nsites, NumericMatrix phi, NumericMatrix theta, NumericVector rho, const int Nchains);

TEST(CARBayesST_deepstate_test,tau2quadform_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix Wtriplet  = RcppDeepState_NumericMatrix();
  qs::c_qsave(Wtriplet,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/tau2quadform/inputs/Wtriplet.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Wtriplet values: "<< Wtriplet << std::endl;
  NumericVector Wtripletsum  = RcppDeepState_NumericVector();
  qs::c_qsave(Wtripletsum,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/tau2quadform/inputs/Wtripletsum.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Wtripletsum values: "<< Wtripletsum << std::endl;
  IntegerVector n_triplet(1);
  n_triplet[0]  = RcppDeepState_int();
  qs::c_qsave(n_triplet,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/tau2quadform/inputs/n_triplet.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_triplet values: "<< n_triplet << std::endl;
  IntegerVector nsites(1);
  nsites[0]  = RcppDeepState_int();
  qs::c_qsave(nsites,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/tau2quadform/inputs/nsites.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nsites values: "<< nsites << std::endl;
  NumericMatrix phi  = RcppDeepState_NumericMatrix();
  qs::c_qsave(phi,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/tau2quadform/inputs/phi.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "phi values: "<< phi << std::endl;
  NumericMatrix theta  = RcppDeepState_NumericMatrix();
  qs::c_qsave(theta,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/tau2quadform/inputs/theta.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta values: "<< theta << std::endl;
  NumericVector rho  = RcppDeepState_NumericVector();
  qs::c_qsave(rho,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/tau2quadform/inputs/rho.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rho values: "<< rho << std::endl;
  IntegerVector Nchains(1);
  Nchains[0]  = RcppDeepState_int();
  qs::c_qsave(Nchains,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/tau2quadform/inputs/Nchains.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Nchains values: "<< Nchains << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    tau2quadform(Wtriplet,Wtripletsum,n_triplet[0],nsites[0],phi,theta,rho,Nchains[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
