// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ECrit_DeepState_TestHarness_generation.cpp and ECrit_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double ECrit(double psiUpstream, double kxylemmax, double c, double d, double pCrit);

TEST(medfate_deepstate_test,ECrit_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector psiUpstream(1);
  psiUpstream[0]  = RcppDeepState_double();
  qs::c_qsave(psiUpstream,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECrit/inputs/psiUpstream.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "psiUpstream values: "<< psiUpstream << std::endl;
  NumericVector kxylemmax(1);
  kxylemmax[0]  = RcppDeepState_double();
  qs::c_qsave(kxylemmax,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECrit/inputs/kxylemmax.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "kxylemmax values: "<< kxylemmax << std::endl;
  NumericVector c(1);
  c[0]  = RcppDeepState_double();
  qs::c_qsave(c,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECrit/inputs/c.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "c values: "<< c << std::endl;
  NumericVector d(1);
  d[0]  = RcppDeepState_double();
  qs::c_qsave(d,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECrit/inputs/d.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "d values: "<< d << std::endl;
  NumericVector pCrit(1);
  pCrit[0]  = RcppDeepState_double();
  qs::c_qsave(pCrit,"/home/akhila/fuzzer_packages/fuzzedpackages/medfate/inst/testfiles/ECrit/inputs/pCrit.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pCrit values: "<< pCrit << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ECrit(psiUpstream[0],kxylemmax[0],c[0],d[0],pCrit[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
