// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// cga_generate_chromosome_DeepState_TestHarness_generation.cpp and cga_generate_chromosome_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector cga_generate_chromosome(NumericVector prob_vec);

TEST(eive_deepstate_test,cga_generate_chromosome_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector prob_vec  = RcppDeepState_NumericVector();
  qs::c_qsave(prob_vec,"/home/akhila/fuzzer_packages/fuzzedpackages/eive/inst/testfiles/cga_generate_chromosome/inputs/prob_vec.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "prob_vec values: "<< prob_vec << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    cga_generate_chromosome(prob_vec);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
