// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// binomialdevfit_DeepState_TestHarness_generation.cpp and binomialdevfit_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List binomialdevfit(NumericVector y, NumericVector trials, NumericMatrix probs, const int nsites, const int Nchains);

TEST(CARBayesST_deepstate_test,binomialdevfit_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/binomialdevfit/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  NumericVector trials  = RcppDeepState_NumericVector();
  qs::c_qsave(trials,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/binomialdevfit/inputs/trials.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "trials values: "<< trials << std::endl;
  NumericMatrix probs  = RcppDeepState_NumericMatrix();
  qs::c_qsave(probs,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/binomialdevfit/inputs/probs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "probs values: "<< probs << std::endl;
  IntegerVector nsites(1);
  nsites[0]  = RcppDeepState_int();
  qs::c_qsave(nsites,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/binomialdevfit/inputs/nsites.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nsites values: "<< nsites << std::endl;
  IntegerVector Nchains(1);
  Nchains[0]  = RcppDeepState_int();
  qs::c_qsave(Nchains,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/binomialdevfit/inputs/Nchains.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Nchains values: "<< Nchains << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    binomialdevfit(y,trials,probs,nsites[0],Nchains[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
