// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// S_diff_DeepState_TestHarness_generation.cpp and S_diff_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double S_diff(NumericVector S);

TEST(ChangePointTaylor_deepstate_test,S_diff_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector S  = RcppDeepState_NumericVector();
  qs::c_qsave(S,"/home/akhila/fuzzer_packages/fuzzedpackages/ChangePointTaylor/inst/testfiles/S_diff/inputs/S.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "S values: "<< S << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    S_diff(S);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
