// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// updatetriplets_rho_DeepState_TestHarness_generation.cpp and updatetriplets_rho_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix updatetriplets_rho(NumericMatrix trips, int nsites, double rho_old, double rho_new, double fixedridge);

TEST(CARBayesST_deepstate_test,updatetriplets_rho_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix trips  = RcppDeepState_NumericMatrix();
  qs::c_qsave(trips,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/updatetriplets_rho/inputs/trips.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "trips values: "<< trips << std::endl;
  IntegerVector nsites(1);
  nsites[0]  = RcppDeepState_int();
  qs::c_qsave(nsites,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/updatetriplets_rho/inputs/nsites.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nsites values: "<< nsites << std::endl;
  NumericVector rho_old(1);
  rho_old[0]  = RcppDeepState_double();
  qs::c_qsave(rho_old,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/updatetriplets_rho/inputs/rho_old.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rho_old values: "<< rho_old << std::endl;
  NumericVector rho_new(1);
  rho_new[0]  = RcppDeepState_double();
  qs::c_qsave(rho_new,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/updatetriplets_rho/inputs/rho_new.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rho_new values: "<< rho_new << std::endl;
  NumericVector fixedridge(1);
  fixedridge[0]  = RcppDeepState_double();
  qs::c_qsave(fixedridge,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/updatetriplets_rho/inputs/fixedridge.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fixedridge values: "<< fixedridge << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    updatetriplets_rho(trips,nsites[0],rho_old[0],rho_new[0],fixedridge[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
