// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// parallelCountNbdm_DeepState_TestHarness_generation.cpp and parallelCountNbdm_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix parallelCountNbdm(NumericVector x, NumericVector y, IntegerVector ReferencePoints);

TEST(dbmss_deepstate_test,parallelCountNbdm_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/dbmss/inst/testfiles/parallelCountNbdm/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector y  = RcppDeepState_NumericVector();
  qs::c_qsave(y,"/home/akhila/fuzzer_packages/fuzzedpackages/dbmss/inst/testfiles/parallelCountNbdm/inputs/y.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "y values: "<< y << std::endl;
  IntegerVector ReferencePoints  = RcppDeepState_IntegerVector();
  qs::c_qsave(ReferencePoints,"/home/akhila/fuzzer_packages/fuzzedpackages/dbmss/inst/testfiles/parallelCountNbdm/inputs/ReferencePoints.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ReferencePoints values: "<< ReferencePoints << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    parallelCountNbdm(x,y,ReferencePoints);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
