// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ataSetNumberOfThreadsForOMP_DeepState_TestHarness_generation.cpp and ataSetNumberOfThreadsForOMP_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

void ataSetNumberOfThreadsForOMP(int num);

TEST(atakrig_deepstate_test,ataSetNumberOfThreadsForOMP_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector num(1);
  num[0]  = RcppDeepState_int();
  std::string num_t = "/home/akhila/fuzzer_packages/fuzzedpackages/atakrig/inst/testfiles/ataSetNumberOfThreadsForOMP/AFL_ataSetNumberOfThreadsForOMP/afl_inputs/" + std::to_string(t) + "_num.qs";
  qs::c_qsave(num,num_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "num values: "<< num << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ataSetNumberOfThreadsForOMP(num[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
