// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rhoquadformcompute_DeepState_TestHarness_generation.cpp and rhoquadformcompute_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double rhoquadformcompute(NumericMatrix Wtriplet, NumericVector Wtripletsum, const int n_triplet, const int nsites, const int ntime, NumericMatrix phi, double rho, NumericVector tau2);

TEST(CARBayesST_deepstate_test,rhoquadformcompute_test){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix Wtriplet  = RcppDeepState_NumericMatrix();
  qs::c_qsave(Wtriplet,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/rhoquadformcompute/inputs/Wtriplet.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Wtriplet values: "<< Wtriplet << std::endl;
  NumericVector Wtripletsum  = RcppDeepState_NumericVector();
  qs::c_qsave(Wtripletsum,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/rhoquadformcompute/inputs/Wtripletsum.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Wtripletsum values: "<< Wtripletsum << std::endl;
  IntegerVector n_triplet(1);
  n_triplet[0]  = RcppDeepState_int();
  qs::c_qsave(n_triplet,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/rhoquadformcompute/inputs/n_triplet.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n_triplet values: "<< n_triplet << std::endl;
  IntegerVector nsites(1);
  nsites[0]  = RcppDeepState_int();
  qs::c_qsave(nsites,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/rhoquadformcompute/inputs/nsites.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nsites values: "<< nsites << std::endl;
  IntegerVector ntime(1);
  ntime[0]  = RcppDeepState_int();
  qs::c_qsave(ntime,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/rhoquadformcompute/inputs/ntime.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ntime values: "<< ntime << std::endl;
  NumericMatrix phi  = RcppDeepState_NumericMatrix();
  qs::c_qsave(phi,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/rhoquadformcompute/inputs/phi.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "phi values: "<< phi << std::endl;
  NumericVector rho(1);
  rho[0]  = RcppDeepState_double();
  qs::c_qsave(rho,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/rhoquadformcompute/inputs/rho.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rho values: "<< rho << std::endl;
  NumericVector tau2  = RcppDeepState_NumericVector();
  qs::c_qsave(tau2,"/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/rhoquadformcompute/inputs/tau2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tau2 values: "<< tau2 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rhoquadformcompute(Wtriplet,Wtripletsum,n_triplet[0],nsites[0],ntime[0],phi,rho[0],tau2);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
