// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// lambdaupdate_DeepState_TestHarness_generation.cpp and lambdaupdate_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix lambdaupdate(const int Nchains, NumericMatrix temp);

TEST(CARBayesST_deepstate_test,lambdaupdate_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector Nchains(1);
  Nchains[0]  = RcppDeepState_int();
  std::string Nchains_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/lambdaupdate/AFL_lambdaupdate/afl_inputs/" + std::to_string(t) + "_Nchains.qs";
  qs::c_qsave(Nchains,Nchains_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Nchains values: "<< Nchains << std::endl;
  NumericMatrix temp  = RcppDeepState_NumericMatrix();
  std::string temp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/CARBayesST/inst/testfiles/lambdaupdate/AFL_lambdaupdate/afl_inputs/" + std::to_string(t) + "_temp.qs";
  qs::c_qsave(temp,temp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "temp values: "<< temp << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    lambdaupdate(Nchains[0],temp);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
